### ISSUE TITLE
hot reloading doesn't work even in the reference example

### ISSUE THREAD

**Issue by dannylin108** [dai-shi/waku#1016]
I used `npm create waku@latest` reference example, but hot reloading of client component doesn't work..

This is the repo https://stackblitz.com/~/github.com/dannylin108/waku-starter

https://github.com/user-attachments/assets/a53d3f9c-563d-43fa-8bbe-81e295eb647e

**Comment by dai-shi** [comment]
Thanks for reporting.

It can repro with stackblitz sandbox too: https://stackblitz.com/edit/github-hwngcz?file=src%2Fcomponents%2Fcounter.tsx,src%2Fpages%2Findex.tsx

 It seems to work with the local machine, so this looks like an issue with StackBlitz. I think it worked once at some point with StackBlitz.
I need someone to help looking into this.

**Comment by dai-shi** [comment]
https://github.com/dai-shi/waku/compare/v0.21.2...v0.21.3
there are so many commits.

**Comment by dai-shi** [comment]
working v0.21.2 + #935: breaks
working v0.21.2 + #932: breaks
working v0.21.2 + #925: breaks
working v0.21.2 + #919: breaks
working v0.21.2 + #903: works
working v0.21.2 + #901: works
working v0.21.2 + #916: works
working v0.21.2 + #918: breaks

that's impossible. #918 doesn't change anything. 😕 

https://github.com/dai-shi/waku/compare/c110fe1c...74c5a6b6 actually includes #886?

working v0.21.2 + #886: breaks
working v0.21.2 + #914: works

https://github.com/dai-shi/waku/compare/34d2c081...20a4dfcf should include the regression.

I think it's #886. Can @tylersayshi look into it please?

**Comment by dai-shi** [comment]
> It seems to work with the local machine

That's my oversight. It looked working, but it wasn't hot reload. It was force reload. It still behaves different for me from the StackBlitz case.

**Comment by dai-shi** [comment]
I'm not exactly sure with the StackBlitz case specifically, but #1021 should fix general cases.
