### ISSUE TITLE
Deploy with Docker?

### ISSUE THREAD

**Issue by Emsu** [dai-shi/waku#1028]
I'm looking at the deploy docs right now and would like to deploy with a plain Docker image but because I don't know the implementation details of Netlify or Vercel or the other providers, not sure what build option works the best for this use case?

Would it be possible to add to the docs an example for a normal Docker deployment?

**Comment by tylersayshi** [comment]
agreed that this should work. you shouldn't need any sort of special config

something like this:

```Dockerfile
FROM node:22-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy app source code
COPY . .

# Build the application
RUN npm run build

# Expose port 80
EXPOSE 80

# Start the application
CMD [ "npm", "run", "start", "--port", "80" ]
```

I can try actually running this tomorrow if there's trouble, but @Emsu let me know how this goes :)

**Comment by rmarscher** [comment]
I gave it a try. I took @tylersayshi's Dockerfile and adjusted it a little to remove the src dir in a second build step.

.dockerignore file:
```
dist
node_modules
```

Dockerfile:
```
# Stage 1: Build the application
FROM node:22-alpine AS build

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Stage 2: Create the final image
FROM node:22-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install --omit=dev

COPY --from=build /usr/src/app /usr/src/app
RUN rm -rf /usr/src/app/src

EXPOSE 80

CMD [ "npm", "run", "start", "--", "--port", "80" ]
```

And then I did:
```
docker build . -t waku-test
docker run -p 3000:80 waku-test
```

and I'm able to open the app at http://localhost:3000. :+1:

**Comment by Emsu** [comment]
Thanks @rmarscher closing this

**Comment by dai-shi** [comment]
No need to improve docs?

**Comment by Emsu** [comment]
@dai-shi I could reopen if you want docs improved. I actually did just find this in the docs when I went to try to add it though:
https://github.com/dai-shi/waku/blob/main/docs/guides/docker.mdx
Is waku.gg not built from the `docs` folder?

**Comment by dai-shi** [comment]
> Would it be possible to add to the docs an example for a normal Docker deployment?

I thought you wanted to add an examples to the docs.

> Is waku.gg not built from the `docs` folder?

It's from README.md only, and `./docs` folder is the place to add supplementary docs. At least for now.
