### ISSUE TITLE
revalidatePath / single Server request with updated rsc data

### ISSUE THREAD

**Issue by aheissenberger** [dai-shi/waku#1033]
When using Next.js it is possible to call a server action and update the interface with **one network request**.
The request to the server will contain the payload and the response will return the result of the server function **and the update serialized data** of the components.

The `router.refresh()`, which is similar to Waku `router.reload()` is disabled and still the interface ist updated based on the use of [`revalidatePath('/')`](https://nextjs.org/docs/app/api-reference/functions/revalidatePath) in the server action `addTodo()`.

How can I achieve this with the Waku framework? Currently I use `router.reload()` which leads to an extra request to the server to update the interface.

Here is a link to the example code: https://v0.dev/chat/IRiWT7TzftT?b=b_QaETSgGhtSy

```tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { addTodo } from '../../lib/actions'

export function AddTodoForm() {
  const [text, setText] = useState('')
  const router = useRouter()

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (text.trim()) {
      await addTodo(text)
      setText('')
      //router.refresh()
    }
  }

  return (
    <form onSubmit={handleSubmit} className="mb-4">
      <input
        type="text"
        value={text}
        onChange={(e) => setText(e.target.value)}
        placeholder="Add a new todo"
        className="border p-2 mr-2"
      />
      <button type="submit" className="bg-blue-500 text-white p-2 rounded">
        Add Todo
      </button>
    </form>
  )
}
```

```ts
'use server'

import { revalidatePath } from 'next/cache'
import { addTodoToStore, toggleTodoInStore, deleteTodoFromStore } from './todos'

export async function addTodo(text: string) {
  await addTodoToStore(text)
  revalidatePath('/')
}
```

Next.js 15 todo app:
https://github.com/aheissenberger/demo-nextjs-todo

Request Payload Next.js 15 todo app:
![SCR-20241204-svfr](https://github.com/user-attachments/assets/7aa7c6d2-8a3d-4386-8205-6e357b9fecfc)
Request Response:
![SCR-20241204-svja](https://github.com/user-attachments/assets/1ad17c24-5528-4378-b19a-8f33b06b41c1)

**Comment by dai-shi** [comment]
> it is possible to call a server action and update the interface with **one network request**.

This is exactly what I wanted, and it was challenging to design the protocol to enable this. (I don't know what Next.js does for its wire protocol.)

Internally, we have the capability `rerender`, but the user-facing API is still undetermined.
Currently, it's this:
https://github.com/dai-shi/waku/blob/4463c56917509ab1103bddef0a75f1a7962fa8b0/examples/21_create-pages/src/components/funcs.ts#L17

We are refactoring some internals and the API might change, but it's definitely something we want to support.

**Comment by aheissenberger** [comment]
I added `unstable_rerenderRoute("/");` to my code and now I get single request UI updates - Waku 🚀 

![waku_single_request_mutation](https://github.com/user-attachments/assets/f883e872-e8cc-4c19-98d9-35a60480b849)


./components/AddTodoForm.tsx:
```tsx
'use client'

import { useState } from 'react'
import { addTodo } from '../lib/actions'

export function AddTodoForm() {
  const [text, setText] = useState('')

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (text.trim()) {
      await addTodo(text)
      setText('')
    }
  }

  return (
    <form onSubmit={handleSubmit} className="mb-4">
      <input
        type="text"
        value={text}
        onChange={(e) => setText(e.target.value)}
        placeholder="Add a new todo"
        className="border p-2 mr-2"
      />
      <button type="submit" className="bg-blue-500 text-white p-2 rounded">
        Add Todo
      </button>
    </form>
  )
}
```

./lib/actions.ts
```ts
'use server'

import { unstable_rerenderRoute } from 'waku/router/server'
import { addTodoToStore, toggleTodoInStore, deleteTodoFromStore } from './todos'

export async function addTodo(text: string) {
  await addTodoToStore(text)
  unstable_rerenderRoute('/') // Waku specific RSC update
}
```

This should be mentioned in the documentation as it is where a RSC framework differs from other data loaders which need a second request to update the UI.

**Comment by dai-shi** [comment]
Yeah, this is something we should emphasize to promote our product.
We will document it for sure when it gets less unstable.

We can also consider adding some docs for unstable features in `./docs`.

**Comment by himself65** [comment]
I saw a case when `unstable_rerenderRoute` is not working... let me reproduce it...

**Comment by himself65** [comment]
```tsx
  <Counter
    callback={async () => {
      'use server'
      await new Promise((resolve) => setTimeout(resolve, 100))
      unstable_rerenderRoute('/')
      await new Promise((resolve) => setTimeout(resolve, 100))
      unstable_rerenderRoute('/')
    }}
  />
```

In this case, the server component will only rerender once? is this expected?

**Comment by dai-shi** [comment]
Yes, it does it once. `unstable_rerenderRoute` is to return server components with the response of server functions. (It's not something like "redirect". And, I'm not confident with the API yet.)

**Comment by himself65** [comment]
Found another edge case:

```tsx
<Counter
    callback={async () => {
      'use server'
      unstable_rerenderRoute('/')
      await new Promise((resolve) => setTimeout(resolve, 1000))
      throw new Error("This is a test error")
    }}
  />
```

This won't trigger rerender?

**Comment by dai-shi** [comment]
Yeah, for now, we await for the promise, so the error wins.
