### ISSUE TITLE
Non-root layouts not loaded in v0.21.8

### ISSUE THREAD

**Issue by rmarscher** [dai-shi/waku#1055]
I think there's a bug in v0.21.8. The list of found path segments with _layout.tsx files is incorrect. It includes `undefined` and `[object]` strings. I think the fix is to use `segment.name` instead of `segment` [edit: and use `index` instead of `index - 1`].

```
--- a/dist/router/create-pages.js
+++ b/dist/router/create-pages.js
@@ -185,10 +185,10 @@ export const createPages = (fn)=>{
     };
     const getLayouts = (spec)=>{
         const pathSegments = spec.reduce((acc, segment, index)=>{
-            if (acc[index - 1] === '/') {
-                acc.push('/' + segment);
+            if (!acc[index] || acc[index] === '/') {
+                acc.push('/' + segment.name);
             } else {
-                acc.push(acc[index - 1] + '/' + segment);
+                acc.push(acc[index] + '/' + segment.name);
             }
             return acc;
         }, [
```

There should probably be a test case to catch this...

**Comment by dai-shi** [comment]
@tylersayshi

**Comment by rmarscher** [comment]
I think this patch is missing something. I'm still getting errors. Working on debugging...

**Comment by rmarscher** [comment]
`index - 1` needed to be `index`. I edited the diff in my original post above.

**Comment by tylersayshi** [comment]
Ah, yea, I don't think we have any e2e tests to check nested layouts.

Sorry about this, I can help look into a fix today

**Comment by dai-shi** [comment]
#1063

**Comment by rmarscher** [comment]
Sorry... @tylersayshi  I think we missed something here. I had to apply this patch to v0.21.9.

```
diff --git a/dist/router/create-pages.js b/dist/router/create-pages.js
index f4e7afb30f4f1a6c7cf6172692c9dcc95e22e210..bcbf749487dbfd24a190f3157806905f6019af9b 100644
--- a/dist/router/create-pages.js
+++ b/dist/router/create-pages.js
@@ -188,7 +188,7 @@ export const createPages = (fn)=>{
             if (index === 0) {
                 acc.push('/' + segment.name);
             } else {
-                acc.push(acc[index - 1] + '/' + segment.name);
+                acc.push(acc[index] + '/' + segment.name);
             }
             return acc;
         }, [
```

**Comment by dai-shi** [comment]
I wonder if we can write a test for it.

**Comment by rmarscher** [comment]
> I wonder if we can write a test for it.

Yeah, I assumed https://github.com/dai-shi/waku/blob/main/e2e/21_create-pages_standalone.spec.ts#L36-L39 would catch... 

For my error, my layout was two levels deep - so maybe we can reproduce by adding /nested/baz/layout.tsx with a /nested/baz/[id]/view.tsx page route.

**Comment by tylersayshi** [comment]
```diff
 -                acc.push(acc[index - 1] + '/' + segment.name);
 +                acc.push(acc[index] + '/' + segment.name);
```

This part of the diff I intentionally omitted, it's not correct, but thanks for sharing still because this does help explain the issue.

I'll add a test to replicate the further nested path and make sure layouts are applied there as well. 👀
