### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED with dev server in v0.21.8

### ISSUE THREAD

**Issue by rmarscher** [dai-shi/waku#1056]
Example error - `Package subpath './router/client.js?v=73b27883' is not defined by "exports"`

This patch fixes it for me:

```
--- a/dist/lib/middleware/dev-server-impl.js
+++ b/dist/lib/middleware/dev-server-impl.js
@@ -136,7 +136,7 @@ const createMainViteServer = (env, configPromise)=>{
         }
         if (file === 'waku' || file.startsWith('waku/')) {
             // HACK `external: ['waku']` doesn't do the same
-            return import(/* @vite-ignore */ file);
+            return import(/* @vite-ignore */ file.split('.')[0]);
         }
         const vite = await vitePromise;
         if (idOrFileURL.startsWith('file://') && idOrFileURL.includes('/node_modules/')) {
```

**Comment by dai-shi** [comment]
I'll look into it. Is it possible to reproduce this with modifying the template a little bit?

**Comment by dai-shi** [comment]
Just to confirm, does reverting this line fix your issue?
https://github.com/dai-shi/waku/pull/1048/files#diff-11b6fc682384040382e2a82f9bb4b98d7357aa85df2353a660ee6c4488a338c9L145-R145

**Comment by rmarscher** [comment]
> Just to confirm, does reverting this line fix your issue? https://github.com/dai-shi/waku/pull/1048/files#diff-11b6fc682384040382e2a82f9bb4b98d7357aa85df2353a660ee6c4488a338c9L145-R145

That does not seem to work. If I log the import, it's this with `idOrFileURL`:

file:///path/to/waku/project/node_modules/waku/dist/minimal/client.js?v=466ecaf7

which causes an error:

Error: Missing Root component
    at Slot (file:///path/to/waku/project/node_modules/waku/dist/minimal/client.js?v=466ecaf7:191:15)

With `file.split('.')[0]`, it's `waku/minimal/client` and that is working.

**Comment by rmarscher** [comment]
OK... instead of splitting on the `.` char, how about this?


```
--- a/dist/lib/middleware/dev-server-impl.js
+++ b/dist/lib/middleware/dev-server-impl.js
@@ -132,7 +132,7 @@ const createMainViteServer = (env, configPromise)=>{
     const loadServerModuleMain = async (idOrFileURL)=>{
         let file = idOrFileURL.startsWith('file://') ? fileURLToFilePath(idOrFileURL) : idOrFileURL;
         if (file.startsWith(wakuDist)) {
-            file = 'waku' + file.slice(wakuDist.length).replace(/\.\w+$/, '');
+            file = 'waku' + file.slice(wakuDist.length).replace(/\.\w+(?:\?v=\w+)?$/, '');
         }
```

**Comment by dai-shi** [comment]
Thanks for looking into it. Splitting with `.` is fine. I was curious if it has ever worked before.
How can I reproduce it? I would like to write a test.

**Comment by dai-shi** [comment]
This is reproduced when I'm trying #1012.

**Comment by dai-shi** [comment]
> This is reproduced when I'm trying #1012.

Oops, that was my misunderstanding.

So, I'm still interested in how to reproduce this error and adding a test.

**Comment by rmarscher** [comment]
I think this is from running in a monorepo.

Create a new folder. Add a package.json file with this:
```
{
  "name": "my-monorepo",
  "private": true,
  "workspaces": [
    "packages/*"
  ]
}
```

Add a pnpm-workspace.yaml file with this:

```
packages:
  - 'packages/*'
```

```
cd packages
pnpm create waku@latest
cd waku-project
pnpm run dev
```


In loadServerModuleMain, since my node_modules is outside the root of the waku project, it includes the full system root path in the request to load the module.

That matches the `file.startsWith(wakuDist)` condition which drops the path to the waku module folder which then causes it to match the next `file.startsWith('waku/')` conditional.

With not in a monorepo, the `file` variable starts with `node_modules` and not the full system path, so it doesn't match wakuDist and it doesn't start with `waku/`, so it hits the part where it includes `/node_modules` which splits on the `?` and gets the correct path to import.

**Comment by rmarscher** [comment]
I can try to find a moment to create a monorepo e2e spec this week. 👍

**Comment by rmarscher** [comment]
I pushed #1079 to track creating a monorepo spec. I think we can go ahead and close this issue and track that effort there.
