### ISSUE TITLE
useRouter push does not load the given page

### ISSUE THREAD

**Issue by pfongkye** [dai-shi/waku#1060]
### What
When pushing to a page with the hook `useRouter_UNSTABLE`, the page does not load on first try. An explicit `router.reloaded()` is needed to make it work.
It worked fine in waku version `0.21.2`
### How to reproduce
Run the project found [here](https://github.com/pfongkye/waku-use-router) and click on the button "Use router to change page"

### Misc
waku version where issue was detected: `0.21.8`
The code can be found [here](https://github.com/pfongkye/waku-use-router/blob/main/src/pages/index.tsx#L16).

**Comment by dai-shi** [comment]
Thanks for reporting! Sounds like a bug.

@pfongkye Can you help us by identifying which version started breaking this? Did you already confirm if v0.21.7 breaks?

@tylersayshi I hope you can help with this. We should write a test.

**Comment by pfongkye** [comment]
Hello, 
@dai-shi sure I'll identify when the issue first occured and let you know.

**Comment by pfongkye** [comment]
Issue is present since `0.12.3` from what I tested.

**Comment by dai-shi** [comment]
v0.21.3, right?

https://github.com/dai-shi/waku/compare/v0.21.2...v0.21.3 has so many changes.

**Comment by dai-shi** [comment]
#895 might be related.

Can you try the codesandbox build? 
https://ci.codesandbox.io/status/dai-shi/waku/pr/895/builds/546877

```
npm i https://pkg.csb.dev/dai-shi/waku/commit/5cdcb8d0/waku
```

**Comment by pfongkye** [comment]
> v0.21.3, right?
> 
Right. Sorry, I mistyped. I'll try the codesandbox build and let you know.

**Comment by pfongkye** [comment]
I tried the codesandbox build using initial version `0.21.2` and it works. However, when I press the back button on the browser, it does not seem to load the previous page.

**Comment by dai-shi** [comment]
> However, when I press the back button on the browser, it does not seem to load the previous page.

You mean, it's a different issue, right?

Hmm.

**Comment by pfongkye** [comment]
Yes. I will see if I have the back button issue on 0.21.8

Yahoo Mail : Recherchez, organisez, maîtrisez 
 
  Le mer., déc. 11, 2024 à 15:21, Daishi ***@***.***> a écrit:   



However, when I press the back button on the browser, it does not seem to load the previous page.


You mean, it's a different issue, right?

Hmm.

**Comment by tylersayshi** [comment]
Starting to dig in here... I've noticed that it is working as expected in node 22 & 23 but not earlier 🤔
