### ISSUE TITLE
Nested layout ignored

### ISSUE THREAD

**Issue by bostjanpisler** [dai-shi/waku#1068]
Nested layout (nested/_layout.tsx) is ignored, page should show h3 element Nested Layout, but doesn't.

Steps to reproduce:
1. clone waku repository
2. cd into examples/11_fs-router
3. npm i
4. npm run dev
5. open localhost:3000/nested/test

![Screenshot 2024-12-14 at 12 00 14](https://github.com/user-attachments/assets/d11a1c1e-127a-493c-b7bf-1ee086d65907)

**Comment by dai-shi** [comment]
Hi, thanks for reporting.
I believe it's the same as #1055.
The fix has already been merged into `main` and it will be included in the next release.

**Comment by dai-shi** [comment]
v0.21.9 has been released. Let us know if that doesn't fix.
