### ISSUE TITLE
`yarn create waku` example doesn't work on windows filesystem

### ISSUE THREAD

**Issue by Sharlottes** [dai-shi/waku#107]
[Fully reproduction video](https://github.com/dai-shi/waku/assets/60801210/aeead86d-4d79-4d07-bf1c-ebe8b4187be5)
note: webpage at 00:31 is just [a CodeSandbox demo](https://codesandbox.io/p/sandbox/waku-example-counter-mdc1yb)

## Environment

|system|version|
| -- | -- |
| node | v18.13.0 |
| package-management | yarn@v1.22.19 |
| os | windows 10 |

## What's happened

Waku's counter example doesn't work on `yarn create waku`, but works on the CodeSandbox demo.

### with `yarn dev`

* `yarn dev` calls `waku dev -with--ssr`

like the above video, the server component is rendered but suddenly disappears with the below error log.
![image](https://github.com/dai-shi/waku/assets/60801210/191e69b1-8ee5-4bae-b902-1c639a0fa8ba)

after several refreshing(<kbd>F5</kbd>), the server component now appears but the client component never seems like the below screenshot. the spinner is still spinning...
![image](https://github.com/dai-shi/waku/assets/60801210/81a12010-309a-465c-b983-f77c595bb8ee)

### with `yarn build`

not only `waku dev`, but also `waku build` has failed. 
It tried to open `C:\Users\user\Documents\GitHub\waku-example\dist\public\RSC\App\props={"name":"Waku"}`, but there is no such file.

build result directory looks like this.
![image](https://github.com/dai-shi/waku/assets/60801210/b61cedfc-d95d-40a0-ad4a-2f941e4eaff5)

<details>
<summary>open full log</summary>

```txt
$ yarn build
yarn run v1.22.19
$ waku build
vite v4.4.4 building SSR bundle for production...
✓ 4 modules transformed.
✓ built in 126ms
vite v4.4.4 building SSR bundle for production...
✓ 3 modules transformed.
dist/entries.js                0.59 kB
dist/assets/App-6a21f0cf.js    1.18 kB
dist/assets/rsc0-6c7571303.js  1.25 kB
✓ built in 54ms
vite v4.4.4 building for production...
✓ 37 modules transformed.
../dist/public/index.html                            1.16 kB │ gzip:   0.57 kB
../dist/public/assets/rsc0-6c7571303.js              0.90 kB │ gzip:   0.38 kB
../dist/public/assets/jsx-dev-runtime-4f08db3d.js   42.59 kB │ gzip:  13.54 kB
../dist/public/assets/main-0ebf788c.js             358.79 kB │ gzip: 108.74 kB
✓ built in 2.01s
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);        
            ^

[Error: ENOENT: no such file or directory, open 'C:\Users\user\Documents\GitHub\waku-example\dist\public\RSC\App\props={"name":"Waku"}'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\user\\Documents\\GitHub\\waku-example\\dist\\public\\RSC\\App\\props={"name":"Waku"}'
}

Node.js v18.13.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

</details>

I've never touched any file or code, just install dependencies and run dev or build directly... am I missing something wrong?

**Comment by dai-shi** [comment]
Thanks for reporting.
It seems like some issues with Windows filesystem.
I will look for solutions/workarounds, but if someone can help investigating this, it would be very helpful.

**Comment by dai-shi** [comment]
Can you please try #108?

https://ci.codesandbox.io/status/dai-shi/waku/pr/108
☝️ Find "Local Install Instructions"

**Comment by Sharlottes** [comment]
oh my god, it completely works fine with no more error logs. 
is there anything to check out more?

![image](https://github.com/dai-shi/waku/assets/60801210/79045436-ee4a-429c-b445-9647234627a6)

**Comment by dai-shi** [comment]
Thanks for confirming. Great to hear.
For now, I will merge #108 later, but I may ask you for any help again.
(It would be nice if we can do automated tests.)
