### ISSUE TITLE
Support typescript path alias

### ISSUE THREAD

**Issue by Sharlottes** [dai-shi/waku#109]
with the below `paths` compiler option on tsconfig,
```json
{
  "compilerOptions": {
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
```

<details>
<summary>see full tsconfig - may not be related on this context</summary>

```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "nodenext",
    "jsx": "react-jsx",
    "strict": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "downlevelIteration": true,
    "noUncheckedIndexedAccess": true,
    "exactOptionalPropertyTypes": true,
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "exclude": ["node_modules"],
  "include": ["**/*.d.ts", "**/*.ts", "**/*.tsx"]
}

```

</details>
    
the Typescript doesn't detect path issues because I and TS  believed waku (or vite) would map the path, but the Counter path in the below code doesn't work.

```tsx
import { Counter } from "@/components/Counter.js";

const App = () => {
  return (
    <div style={{ border: "3px red dashed", margin: "1em", padding: "1em" }}>
      <h1>Hello!!</h1>
      <h3>This is a server component.</h3>
      <Counter />
    </div>
  );
};

export default App;
```

waku will throw error on the terminal below. and cannot show entire elements. 
this may be expected behavior because `App` component is the root component, which doesn't have any more error boundaries from the parent.
![image](https://github.com/dai-shi/waku/assets/60801210/840f4202-c50b-4f0e-91e0-121e6bc0fddd)

```bash
[vite] Error when evaluating SSR module /src/components/App.tsx: failed to import "@/components/Counter.js"
|- Error: Cannot find module '@/components/Counter.js' imported from 'C:/Users/user/Documents/GitHub/waku-example/src/components/App.tsx'
    at nodeImport (file:///C:/Users/user/Documents/GitHub/waku-example/node_modules/vite/dist/node/chunks/dep-abb4f102.js:55911:25)
    at ssrImport (file:///C:/Users/user/Documents/GitHub/waku-example/node_modules/vite/dist/node/chunks/dep-abb4f102.js:55813:30)
    at eval (C:/Users/user/Documents/GitHub/waku-example/src/components/App.tsx:4:37)
    at async instantiateModule (file:///C:/Users/user/Documents/GitHub/waku-example/node_modules/vite/dist/node/chunks/dep-abb4f102.js:55875:9)   
```

> **note**: source code is Waku's Counter example. just run `yarn create waku` to get full source.

of course, if i change "@/components/Counter.js" to "./Counter.js", it works fine. but i hope waku supports typescript path.

**Comment by dai-shi** [comment]
Thanks for the suggestion!
Yeah, your feature request seems valid.
Unfortunately, I'm not sure how easy it is for the current architecture.
We'll see how it goes before reaching v1. So, stay tuned.
Meanwhile, if anyone is interested, please feel free to dig into it and share the findings.

**Comment by himself65** [comment]
Could you add plugin `vite-tsconfig-paths` in `vite.config.ts`?

**Comment by dai-shi** [comment]
https://github.com/dai-shi/waku/pull/148/files#diff-bc6a39d2294475b104b5951670a0a61ecbff69714f51da54ae373fd3bf13cc22R17 seems good.
