### ISSUE TITLE
Support hot reload for server components

### ISSUE THREAD

**Issue by tom-sherman** [dai-shi/waku#113]
Unless I'm mistaken `waku dev` only supports full-page reload with HMR right now, could it support react fast refresh?

**Comment by dai-shi** [comment]
Fast refresh should work if you only modify client components. If a file is used both by client components and server components, it will full reload.

**Comment by tom-sherman** [comment]
Ah cool. It would be great to support fast refresh of server components then! This is possible in Next.js.

**Comment by dai-shi** [comment]
Yeah, if it's technically possible, we could do it. As Vite (probably) supports only fast refresh of client components, to support that of server components, Waku would need its own mechanism...

**Comment by tom-sherman** [comment]
Yep. I'm hoping vite allows you to extend the websocket messages so that it could say something like "{type: refresh, component: App}` and that would trigger Waku client to re-fetch the RSC.

**Comment by ojj1123** [comment]
@dai-shi 
Out of curious, I was wondering if I could find where you refer to make [vite-plugin-rsc-reload](https://github.com/dai-shi/waku/blob/c599251c69add15be9ad1f7d42a4116deb66149d/packages/waku/src/lib/plugins/vite-plugin-rsc-reload.ts).

I try to find the references about RSC fast refresh, but I could do it just in Next.js. Vercel made [HotReloaderWebpack](https://github.com/vercel/next.js/blob/fc25fcef3edc488c17ea6da7259a352e2dcca1d8/packages/next/src/server/dev/hot-reloader-webpack.ts#L186) module to fast-refresh [a various of changes](https://github.com/vercel/next.js/blob/7c7d981b2d3b5a3025a0a4f17e82d2644e3b5286/packages/next/src/server/dev/hot-reloader-types.ts#L10-L26) such as `clientComponentChanges`, `serverComponentChanges`, etc.

What I make vite rsc fast-refresh plugin is a bit challenge, but I would like to invest it

**Comment by dai-shi** [comment]
Yeah, it will be challenging. We need to detect the server component changes and then do RSC refetch.

**Comment by dai-shi** [comment]
this has a priority after v0.19.0.
i'll eventually work on it, but not soon. meantime, feel free to tackle it.

**Comment by ojj1123** [comment]
i was investigating but It's a bit hard for me to solve this issue cause i don't have enough knowledge about the vite bundler.
but yeah i try to do this :)
If someone have the solution, feel free to catch it

**Comment by dai-shi** [comment]
Please feel free. We are all new to this stuff. You will learn something trying this, even if you don't reach the final solution. Challenging is good.

**Comment by dai-shi** [comment]
As it seems there is a high demand on this #404, I will work on this with priority.
