### ISSUE TITLE
hooks cannot be used in server component

### ISSUE THREAD

**Issue by PerfectPan** [dai-shi/waku#114]
I try to use hooks in server component, but it reported that 「Cannot read properties of null (reading 'useContext')」

This bug is also similar with https://github.com/dai-shi/waku/pull/103#issuecomment-1633861236 since react-tweet use 「useMemo」 in the server component

codesandbox: https://codesandbox.io/p/sandbox/waku-example-counter-forked-4rg8fz?file=%2Fsrc%2Fcomponents%2FApp.tsx%3A7%2C38

I figured it out the reason, but I do not know how to fix it.

vite.ssrLoadModule will resolve package with override conditions https://github.com/vitejs/vite/blob/main/packages/vite/src/node/ssr/ssrModuleLoader.ts#L132. So when the user code bundled in ssrLoadModule, the react package will be resolved as index.js instead of react.shared-subset.js because of lacking react-server condition.

And the react-dom-server package resolve react as react.shared-subset.js, so there will appear two React instance.

After I forcely changed the vite code by adding react-server condition, it worked.
![CleanShot 2023-08-01 at 00 03 47@2x](https://github.com/dai-shi/waku/assets/24316656/52f71a68-25f6-4326-8ba8-31713bd54561)

Obviously it is not a correct way to solve this problem and I have no idea how to fix it, so I leave a message about what I found here.

**Comment by nksaraf** [comment]
Yup!!! This requires a PR in vite: https://github.com/vitejs/vite/pull/13487 I made one but haven't got it landed. Basically whenever does leaves the resolution to node for some cases, it doesn't pass the conditions forward.

**Comment by PerfectPan** [comment]
I just try the modfied code to reproduce the issue https://github.com/dai-shi/waku/issues/96#issuecomment-1657454131 https://github.com/dai-shi/waku/issues/111. 

And it seems all work fine, so maybe after the above pr merged in the vite or just patching the package in advance can solve those issues.

**Comment by dai-shi** [comment]
Much appreciated to both of you!!!
