### ISSUE TITLE
Custom preloaders?

### ISSUE THREAD

**Issue by Kelin2025** [dai-shi/waku#116]
Right now Waku displays its own spinner:
<img width="439" alt="image" src="https://github.com/dai-shi/waku/assets/4208480/88d8760f-9190-4530-94c3-6a8a38ed026b">

I tried wrapping a client component into `<Suspense fallback={...}>`
But it shows Waku's spinner first and then switches to suspense fallback for a split second

Is there a way to use your own preloader?
- If so, how do we make it?
- If not, is it planned?

Thanks!

**Comment by dai-shi** [comment]
I mean the Waku's spinner is basically used before React loads.
So, if you show skeleton with `<Suspense>` in your React code, it should work.
If the flickering is the issue, only the solution I can think of now is to hide the Waku's spinner.

---
With SSR, things are a little more complicated, the getFallback config can solve it, but I see it's not ideal for customization.
If you put Suspense **everywhere** for the server/client boundary,
```js
 const getFallback = () => { 
   return "waku/server#ClientOnly"; 
 }; 
```
might work.

Let me know how it goes.
