### ISSUE TITLE
sh: waku: command not found

### ISSUE THREAD

**Issue by reggi** [dai-shi/waku#121]
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:.

changing to " link:." to  "file:." in package.json fixes

https://stackoverflow.com/questions/74679689/unsupported-url-type-link-while-using-npm

➜  waku git:(main) ✗ node -v
v18.17.1
➜  waku git:(main) ✗ npm -v
9.6.7

**Comment by dai-shi** [comment]
Developing Waku itself (including running example in the repo) requires `pnpm`, but using waku and developing your app doesn't.

Please try `npm create waku@latest`.
