### ISSUE TITLE
Suggestion for website

### ISSUE THREAD

**Issue by vasucp1207** [dai-shi/waku#125]
I see the `waku` website looks like it was built from scratch, Isn't a good idea to use an existing `SSG` framework to power the website as it is easy to maintain and provides a complete solution overall?

**Comment by dai-shi** [comment]
Waku's website is built with Waku. It's important to improve the website, but it's meaningful to build it with Waku. If we find an issue or feature request, we should improve Waku itself.

**Comment by vasucp1207** [comment]
Got it.
