### ISSUE TITLE
[Discuss]: Compare with Other RSC frameworks.

### ISSUE THREAD

**Issue by JiangWeixian** [dai-shi/waku#14]
Thanks for awesome works, I usually use Vite most of the time, and I am very happy to have a Vite-based server-side framework.

In early stage, Shopify https://github.com/Shopify/hydrogen-v1 implement a SSR framework(with RSC) based on Vite. It contains:

- some vite rsc plugins
- `react-server-dom-vite` (like `react-server-dom-webpack`)

Looks like we can build on top of those packages

**Comment by dai-shi** [comment]
https://github.com/cyco130/vite-rsc will be the work to become something we can hopefully build on.

**Comment by dai-shi** [comment]
It doesn't seem to happen very soon https://github.com/cyco130/vite-rsc/discussions/8, so my plan is to do things in this repo 👉 #21.

**Comment by dai-shi** [comment]
Let's continue discussion in #25.
