### ISSUE TITLE
bundlephobia badge incorrect status

### ISSUE THREAD

**Issue by himself65** [dai-shi/waku#155]
I think bundlephobia doesn't support `exports` fields for now. Do we have to add `module` in the `package.json`?

https://github.com/pastelsky/bundlephobia/issues/457#issuecomment-764855435

https://bundlephobia.com/package/waku

**Comment by dai-shi** [comment]
Let's wait for bundlephobia to fix.
We can remove the badge otherwise.

**Comment by dai-shi** [comment]
> We can remove the badge otherwise.

It's done.
