### ISSUE TITLE
Missing `dist/cli.js` from `create-waku`

### ISSUE THREAD

**Issue by Asuka109** [dai-shi/waku#168]
It seems the last release is broken.

![image](https://github.com/dai-shi/waku/assets/18379948/96e92620-4940-40c6-ade8-560ff0f8d864)

![image](https://github.com/dai-shi/waku/assets/18379948/b8745f1a-1eb3-42b9-b726-cb37f2842c6e)

**Comment by dai-shi** [comment]
Thanks for reporting. 
Seems like I broke something around build. 


See #167

**Comment by dai-shi** [comment]
create-waku v0.6.2 is published.
