### ISSUE TITLE
Refactor: implement DEV only logic as vite plugins

### ISSUE THREAD

**Issue by dai-shi** [dai-shi/waku#219]
After #218, I think we can move some code (including Worker) into new vite plugins.

**Comment by dai-shi** [comment]
@Aslemammad I think you can try this after #324.
What I have in mind is creating many small plugins (like what we do now) and one plugin that calls all of them, that is for easier use.

**Comment by Aslemammad** [comment]
Yep! We can do that.

**Comment by Aslemammad** [comment]
I'll get to all of these issues soon, just a bit busy on my side. Thanks.

**Comment by dai-shi** [comment]
For the next release, #323 and #344 are more important.
Furthermore, I might be refactoring something soon, and maybe this issue can be delayed. (at the same time, I would like to know the approach, so giving a try/draft would be good.)

**Comment by dai-shi** [comment]
After some investigations, it feels like eliminating worker is possible if we somehow support CommonJS #110 without `external`insing or `commonjs`-transpiling selectively, and transpile all commonjs packages including React libs.

**Comment by dai-shi** [comment]
#445 goes the other way around. If it goes well, we will likely keep worker for quite a while. So, we should move this issue forward with the worker. It means this issue is ready to tackle.

**Comment by dai-shi** [comment]
Let's give this up for now. Our middleware architecture goes against to it. Let's revisit it when we understand the requirement better.
