### ISSUE TITLE
From the perspective of a React user, what is the goal of Waku?

### ISSUE THREAD

**Issue by brillout** [dai-shi/waku#25]
Thanks for all your wonderful work on State Management. It has been very refreshing.

I'm actually quite curious as to what the goal of Wakuwork is in terms of what the pros of using Wakuwork will be compared to Next.js?

**Comment by dai-shi** [comment]
From the perspective of a React user, the goal would be to provide:
- a replacement for client-only vite/react app
- RSC practice with client-first approach
- opinionated RSC framework that is far thinner than Next.js
- exploring client state integration: #11
- router-agnostic React framework: https://twitter.com/dai_shi/status/1647132335694028800

Hope it helps.

**Comment by dai-shi** [comment]
While the points I made are still valid, this is a bit old and we have an updated and broader view.
Please see new README and our website. Free free to open a new discussion.
