### ISSUE TITLE
12_css e2e test

### ISSUE THREAD

**Issue by Aslemammad** [dai-shi/waku#265]
1. #262  
> Thanks for the fix.
It would be nice if you can add e2e tests, because we can then know if something breaks with refactoring. (not only for this 12_css example, but also for others). Please give it a try whey you have a chance.

**Comment by dai-shi** [comment]
Can you integrate this with #186, or make this issue title specific to an e2e test case for 12_css?

**Comment by dai-shi** [comment]
let's merge this into #186

**Comment by dai-shi** [comment]
<img width="149" alt="image" src="https://github.com/dai-shi/waku/assets/490574/3623fc3d-a565-43cf-ac73-d729efad2234">
