### ISSUE TITLE
add toturial of deply vercel and improve CLI option to control output (vercel/cloudflare/node.js)

### ISSUE THREAD

**Issue by himself65** [dai-shi/waku#269]

**Comment by dai-shi** [comment]
I added something minimal in #267, please feel free to improve it.
If the tutorial is rather long, consider making it in a discussion and have a link in README for a start.

**Comment by dai-shi** [comment]
Thanks to #355, `vercel` no longer mis-detect waku app as vite app. So, `vercel` command just works.
