### ISSUE TITLE
environment variables improvement

### ISSUE THREAD

**Issue by himself65** [dai-shi/waku#292]
treat `WAKU_PUBLIC_` prefix as public env vars that can only be used in client side rendering (or ssr?)

others can be used in RSC

**Comment by dai-shi** [comment]
Implementation-wise, it's a bit complicated as we want to support both Node and non-Node. I'll work on it later.

**Comment by himself65** [comment]
Cloudflare: https://developers.cloudflare.com/workers/configuration/environment-variables/#add-environment-variables-via-wrangler

Deno: https://examples.deno.land/environment-variables

**Comment by dai-shi** [comment]
Thanks. So, I'm sure Waku core should simply accept an env object and adapters for Node.js, CFW, and Deno translate to it.

**Comment by dai-shi** [comment]
I would like to avoid using `process.env` in the source code, even though they are transpiled. Maybe, `__WAKU_ENV__` or something.
