### ISSUE TITLE
refactor idea: worker-api/impl

### ISSUE THREAD

**Issue by dai-shi** [dai-shi/waku#308]
I thought we needed to stream data through message port, but looking at
https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Transferable_objects
can we actually transfer `ReadableStream`. Does it work on Node too?

**Comment by himself65** [comment]
yes, https://github.com/nodejs/node/blob/4d3923aabaa6d57dc9dc3c554434fa69410c3d55/benchmark/webstreams/js_transfer.js#L47

**Comment by dai-shi** [comment]
nice, it will simplify the code a bit.

**Comment by Aslemammad** [comment]
working on this
