### ISSUE TITLE
Question: Routing support

### ISSUE THREAD

**Issue by LizAinslie** [dai-shi/waku#351]
I was looking around the Poimandres Discord and found your profile where I noticed Waku! After looking further into it and playing around with it, I really want to use Waku in my projects, but there's one catch for me: I would really like to take advantage of the typesafety provided by something like the [Tanstack Router](https://tanstack.com/router/).

I'm wondering if there is support for bringing my own router, or if not is it planned?

All the best! - Lizzy
I'm `@LizzyTheWitch` on Discord, by the way. You can reach me there instead if you like.

**Comment by LizAinslie** [comment]
Oh, i just found #272, will be closing now to continue there!

**Comment by dai-shi** [comment]
> I was looking around the Poimandres Discord and found your profile where I noticed Waku!

That's wonderful.
