### ISSUE TITLE
Duplicated hoistable elements

### ISSUE THREAD

**Issue by ojj1123** [dai-shi/waku#365]
I updated waku version at 0.19.0-alpha.2
But is it bug? The hoistable elements is duplicated
I know you make this PR https://github.com/dai-shi/waku/pull/289 and this feature is in `v0.19.0-alpha`

<img width="513" alt="스크린샷 2024-01-11 오후 10 25 28" src="https://github.com/dai-shi/waku/assets/33178048/a43d3e1a-5583-4064-8fe8-2d8e299db7ff">

repro: https://github.com/ojj1123/info/pull/5
you can see this issue here: https://info-git-feat-migrate-waku-ojj1123.vercel.app/

**Comment by dai-shi** [comment]
Thanks for reporting. Hm, no, I didn't see such duplication before.
Appreciated if you can dig in it further.

**Comment by ojj1123** [comment]
Okay but it's not occured at [this examples](https://github.com/dai-shi/waku/tree/main/examples) you made
anyway i will investigate this issue

**Comment by dai-shi** [comment]
right, it doesn't happen in our examples. so, your strategy would be to compare the two.

**Comment by ojj1123** [comment]
It's a bit weird 😭  I investigated it comparing [my repo](https://github.com/ojj1123/info/pull/5) with [12_css example](https://github.com/dai-shi/waku/tree/main/examples/12_css). **I found the reason: maybe cause of the dependencies.**
This issue is reproduced below the situation at `waku@0.19.0-alpha.2`:

### When including `react-server-dom-webpack` as dependency

Each time I run `pnpm dev` alternately, the two situations below alternate:
The elements(`div` tag at this example) appear below or above `script` containing the RSC payload.
|the elements below `script` (buggy 😭)|the elements above `script` (correct)|
|---|---|
|![스크린샷 2024-01-14 오전 2 12 16](https://github.com/dai-shi/waku/assets/33178048/b6504d77-b592-43ec-8276-c6fb11a75329)|![스크린샷 2024-01-14 오전 2 13 29](https://github.com/dai-shi/waku/assets/33178048/0c7e4e3b-30fc-4ae1-8125-45fd6446dc3d)|

But The duplicated hoistable elements is always occured at PRD.

### How to solve
I saw you did [reduce peer dependencies #355](https://github.com/dai-shi/waku/pull/355) including `react-server-dom-webpack`, etc. i've done it so I resolved this issue.
that is, If no `react-server-dom-webpack` as dependency, No issue that the hoistable elements is duplicated.

I don't think this issue is critical right now. If this issue is occured at `waku@0.19.0`, what about digging this issue again?

**Comment by dai-shi** [comment]
Can you try npm instead of pnpm?

See also: https://github.com/dai-shi/waku/issues/371#issuecomment-1890808818

**Comment by ojj1123** [comment]
> Each time I run pnpm dev alternately, the two situations below alternate:
> The elements(div tag at this example) appear below or above script containing the RSC payload.

It's same if RSDW is in `dependencies` or `devDependencies`.

## Repro
> _Can you try npm instead of pnpm?_

```
pnpm add -D react-server-dom-webpack@canary
npm run dev
```

**Comment by ojj1123** [comment]
I will try to use `waku@v0.19.0-beta.1`

**Comment by ojj1123** [comment]
Oh I didn't check this PR https://github.com/dai-shi/waku/pull/321
This issue was occured because i used `__WAKU_SSR_ENABLED__`.
`globalThis.__WAKU_SSR_ENABLED__` was `undefined` so `createRoot` was called inside browser.

I replace `globalThis.__WAKU_SSR_ENABLED__` with `import.meta.env.WAKU_HYDRATE` so i can resolve the duplicated hoistable elements issue.
https://github.com/ojj1123/info/pull/5/commits/e5e27dfc9b134812d2020ffd5350033b55e22044

I'll close this issue :)
