### ISSUE TITLE
unresolved environment variable `import.meta.env.WAKU_HYDRATE`

### ISSUE THREAD

**Issue by himself65** [dai-shi/waku#380]
<img width="580" alt="image" src="https://github.com/dai-shi/waku/assets/14026360/1417250a-0dd1-4531-a579-4f159be19b07">

**Comment by himself65** [comment]
https://github.com/dai-shi/waku/blob/66339e5937e418ceec77c5b944bc28704f2ee7d9/packages/waku/src/client.ts#L21-L25

Should we add some waku env vars into this?

**Comment by dai-shi** [comment]
Is it TypeScript only issue?
Why does it complain with `Record<string, string>`??

**Comment by himself65** [comment]
I'm using WebStorm, let me see what happened on VSCode

**Comment by himself65** [comment]
Ok, looks good on vscode
<img width="622" alt="image" src="https://github.com/dai-shi/waku/assets/14026360/58abf9e4-eb85-40b5-95d5-c4be47857e54">

**Comment by himself65** [comment]
OK,

1. env is unresolved is IDE only issue: https://youtrack.jetbrains.com/issue/WEB-62135/Vite-import.env-is-unresolved
2. I think we should declare `WAKU_HYDRATE` on top?

**Comment by dai-shi** [comment]
We could declare it if it helps. It feels somewhat internal and not super necessary. But, it doesn't hurt, so I'm fine.

(btw, I think there's room for improvement for better TypeScript support in general. Not only our internal implementations are 100% typed, but also public API isn't 100% typed.)

**Comment by himself65** [comment]
I will keep this issue until we have enough users to question about such things

**Comment by dai-shi** [comment]
We no longer use `import.meta.env.WAKU_HYDRATE`. We don't know the future though.
