### ISSUE TITLE
`getEnv` is not working on vercel edgeless function

### ISSUE THREAD

**Issue by himself65** [dai-shi/waku#388]
https://github.com/himself65/waku-pokemon

I created a demo to connect backend database. And the 500 error on prod

https://waku-pokemon-p86nl519u-alex-yang.vercel.app/
![image](https://github.com/dai-shi/waku/assets/14026360/d1bb9aec-8c30-4a46-ad34-27885efbf3b2)

I read the output file

```js
function getEnv(key) {
  return globalThis.__WAKU_PRIVATE_ENV__[key];
}
```

![image](https://github.com/dai-shi/waku/assets/14026360/48c84cc8-f8f8-43f8-9cf6-d67a3e5a3ab4)

<img width="662" alt="image" src="https://github.com/dai-shi/waku/assets/14026360/a3dc8cdc-da34-42fa-ac0f-f55808ab1e02">

`__WAKU_PRIVATE_ENV__` is not defined in the output files

**Comment by himself65** [comment]
yeah, reason is I used `getEnv` in the global context, but waku will set env map after you connect it

**Comment by himself65** [comment]
See: https://github.com/himself65/waku-pokemon/pull/1

**Comment by dai-shi** [comment]
My hope is #395 fixes this. Can you please try it?
