### ISSUE TITLE
dynamic page cause `unknown root exit status.`

### ISSUE THREAD

**Issue by himself65** [dai-shi/waku#391]
![image](https://github.com/dai-shi/waku/assets/14026360/4460e43a-7b34-4753-bdf4-5d24613b2ce0)

**Comment by himself65** [comment]
See:

https://github.com/himself65/waku-issue-391
https://waku-issue-391.vercel.app/

**Comment by himself65** [comment]
Way to reproduce:

```shell
pnpm create waku
\n\n\n
cd project
```

change related code to

```ts
  createPage({
    render: 'dynamic', // <-- from 'static'
    path: '/',
    component: HomePage,
  });
```

deploy to vercel

**Comment by himself65** [comment]
workaround: remove `--with-ssr`

**Comment by dai-shi** [comment]
I wonder if #395 fixes or not.

**Comment by himself65** [comment]
i will try it

**Comment by dai-shi** [comment]
I just tried, and it doesn't seem #395 helps at all.
