### ISSUE TITLE
difference between `workerd` and `worker` in conditions

### ISSUE THREAD

**Issue by himself65** [dai-shi/waku#393]
I noticed that waku is using `workerd` in the import conditions.

https://github.com/dai-shi/waku/blob/a7e909f87bb8965a781323ba18902fbb454e5e9f/packages/waku/src/lib/handlers/dev-worker-impl.ts#L139-L140

I think this is not correct. `workerd` is an alias for Cloudflare workers; I guess you are mentioning `worker`, which is for the web worker.

https://developers.cloudflare.com/workers/wrangler/bundling/#conditional-exports

**Comment by himself65** [comment]
some examples in real world

https://github.com/facebook/react/blob/5c607369ceebe56d85175df84b7b6ad58dd25e1f/packages/react-dom/package.json#L56-L59

**Comment by dai-shi** [comment]
https://github.com/facebook/react/blob/5c607369ceebe56d85175df84b7b6ad58dd25e1f/packages/react-server-dom-webpack/package.json#L52

I specifically meant `server.edge`.

We can try `server.browser` if it has the capability we use, but we need to adjust everything.

**Comment by dai-shi** [comment]
This is intentional for the moment. I wonder how we do it in the future. Each approach seems to have pros and cons.

**Comment by dai-shi** [comment]
https://github.com/dai-shi/waku/pull/394#issuecomment-1938897961
> > My idea is to use different outputs for different distributions.
> 
> We may try that in the future, once it has settled a bit more.

**Comment by dai-shi** [comment]
somewhat related: https://github.com/dai-shi/waku/pull/480
