### ISSUE TITLE
misleading error when import client module in server component

### ISSUE THREAD

**Issue by himself65** [dai-shi/waku#402]
```tsx
// "use client" <-- forget to add this
import { useFormState } from "react-dom"
import { generateResponse } from '../actions/chat.js'

export function Client () {
  const [state, dispatch] = useFormState(
    generateResponse,
    null
  )
  return (
    <div>
      {state}
      <button
        onClick={() => {
          dispatch()
        }}
      >
        Generate Response
      </button>
    </div>
  )
}

```

<img width="349" alt="image" src="https://github.com/dai-shi/waku/assets/14026360/16bbacb5-d082-49e9-9029-c87353726ced">

**Comment by dai-shi** [comment]
nice catch. let's target v0.20.

**Comment by dai-shi** [comment]
```
Error: [vite] Named export 'useFormStatus' not found. The requested module 'react-dom' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'react-dom';
const {useFormState, useFormStatus} = pkg;
```
is the error I get now.

Do you think we can improve it more?

**Comment by Aslemammad** [comment]
@himself65 What do you think the error should be? What do you suggest for that?

**Comment by himself65** [comment]
"Seems like you are importing Client Component on the server side. Please add "use client" on the file" or something.

**Comment by dai-shi** [comment]
> try to remove "react-server" condition and compile again, if it works so it's a CSC

Wouldn't it be too much work to tackle for the moment?

**Comment by ojj1123** [comment]
[useFormState was deprecated](https://react.dev/blog/2024/04/25/react-19#new-hook-useactionstate), so as `waku@0.21.0-beta.2`, I tested to import [`useActionState`](https://react.dev/reference/react/useActionState) in RSC. it occurs the error below:

![스크린샷 2024-07-15 01 40 47](https://github.com/user-attachments/assets/94e1d048-5b25-4d56-a0a3-7346c30e06ef)

**Comment by dai-shi** [comment]
Thanks. It feels less misleading.

I'll close this issue as it's mitigated.

But, in general, error messages are not good and there's huge room for improvement. It's just not only this.
