### ISSUE TITLE
Error: Element type is invalid. Received a promise that resolves to: undefined. Lazy element type must resolve to a class or function.

### ISSUE THREAD

**Issue by Kumneger0** [dai-shi/waku#434]
hi there 
i was just exploring waku and i got  an error when i tried to import client component into server component here is my code 

```jsx
"use client";
function SubmitButton({ addTodo }: { addTodo: () => void }) {
  return (
    <div>
      <button onClick={() => addTodo()} type="button">
        add
      </button>
    </div>
  );
}

export default SubmitButton;

```

```js 

"use server";
import { type RenderContext } from "waku/server";
export const todos: Array<{ name: string; completed: boolean }> = [
  { name: "initial todo", completed: false },
];

addTodo const addTodo = (ctx: RenderContext) => {
  todos.push({name : 'new todo", completed:false})
  ctx.rerender("waku");
};
```

```jsx
import { addTodo, todos } from "./actions.js";
import SubmitButton from "./submitButton.js";

export const Todos = () => {
  return (
    <section className="border-blue-400 -mx-4 mt-4 rounded border border-dashed p-4">
      <div>
        {todos.map(({ name, completed }) => {
          return (
            <div>
              {name} <input type="checkbox" defaultChecked={completed} />
            </div>
          );
        })}
      </div>
      <input type="text" name="name" />
      <SubmitButton addTodo={addTodo} />
    </section>
  );
};

```
Upon running this code, I receive the error: "Element type is invalid. Received a promise that resolves to: undefined. Lazy element type must resolve to a class or function.

**Comment by dai-shi** [comment]
Thanks for trying out and reporting the issue!

Our error message is very bad. There is huge room for improvement. #402.

I'm not sure what's wrong immediately from the code.

The difference from examples/05_actions is that exporting `getTodos` function instead of `todos` variable. Not sure if it helps, but can you try?

Also, you misuse `rerender`.
It must be `this.rerender(...)`, which means the function must not be an arrow function.
We understand this doesn't look like community standard and will revisit the API in the future.

**Comment by Kumneger0** [comment]
@dai-shi Thanks for your responses. As you suggested, I've made changes to my code similar to those in examples/05_actions.
```jsx

"use server";
import { type RenderContext } from "waku/server";
const todos: Array<{ name: string; completed: boolean }> = [
  { name: "initial todo", completed: false },
];

export function getTodos() {
  return todos;
}

export function addTodo(this: RenderContext) {
  todos.push({ name: "new todo", completed: false });
  this.rerender("waku");
}
```

However, I'm still receiving the same error

**Comment by Kumneger0** [comment]
No. i'll try and i'll let you know

**Comment by Kumneger0** [comment]
hi there
 I've been able to successfully import and use the component when it's exported as a named export, but encounter an error when it's exported as a default export.
 
```jsx
//error
export default function SubmitButton(props){
//jsx
}

```

```jsx 
//no-error
export function  SubmitButton(props){
//jsx
}
```


[Screencast from 01-30-2024 09:47:41 AM.webm](https://github.com/dai-shi/waku/assets/93655689/558e5135-2874-4964-81c9-a15f561923a2)

**Comment by dai-shi** [comment]
Thanks for the reproduction. That seems pretty minimal.

I assume it's a bug. Can anyone dig into it?

To confirm, is it dev only issue, or both for dev (`waku dev`) and prd (`waku build` && `waku start`)?

**Comment by Kumneger0** [comment]
> To confirm, is it dev only issue, or both for dev (`waku dev`) and prd (`waku build` && `waku start`)?

only in dev mode it works fine in prd mod
