### ISSUE TITLE
hydrateRoot(...): Target container is not a DOM at waku website

### ISSUE THREAD

**Issue by ojj1123** [dai-shi/waku#435]
after this commit e3cf231499b99f2e89c163339abb82707e1039c2, the error below is occured.
I was running on waku website. This PR https://github.com/dai-shi/waku/pull/431 just restore vendor prefix. something is special?

![스크린샷 2024-01-29 오전 12 38 25](https://github.com/dai-shi/waku/assets/33178048/45eaa7b1-5faf-42f6-a944-1f42e4cc7f84)

**Comment by dai-shi** [comment]
oooookay, thanks for the catch.
@sandren @Aslemammad any ideas?

**Comment by sandren** [comment]
> oooookay, thanks for the catch. @sandren @Aslemammad any ideas?

It seems components that return different values based on state are breaking hydration in local dev:
https://github.com/dai-shi/waku/blob/main/packages/website/src/components/client-only.tsx#L14
