### ISSUE TITLE
CSS modules broken in DEV after #427

### ISSUE THREAD

**Issue by dai-shi** [dai-shi/waku#439]
`npm run examples:dev:09_cssmodules`

### Before #427 

<img width="276" alt="image" src="https://github.com/dai-shi/waku/assets/490574/c64c8d3b-825a-4787-b21f-f8c7c01c6bfb">

### After #427 

<img width="280" alt="image" src="https://github.com/dai-shi/waku/assets/490574/fd89def0-ff2d-4d75-9ab9-1d957faf6029">

**Comment by dai-shi** [comment]
Sorry, I overlooked it and we don't have an e2e test.

@Aslemammad Can you investigate it please?

**Comment by Aslemammad** [comment]
Oh ok, I'll try to get into it in the next few days, is that ok? and if yes, please assign me!
