### ISSUE TITLE
React Float for the current CSS implementation

### ISSUE THREAD

**Issue by Aslemammad** [dai-shi/waku#508]
> Sophia — 16/02/2024 00:50
This might be what we need to avoid FOUC w/o hacks:
Daishi Kato — 16/02/2024 03:44
That's what I originally thought: use React Float to inject style in DEV.
As it turns out, Vite handles style HMR pretty differently, and it's @Mohammad Bagher 's take to support it in Waku as Vite way.

I found out that React will wait for the prefetch APIs (React Float), so I believe that'd be helpful for us to integrate [React Float](https://react.dev/reference/react-dom#resource-preloading-apis) for css impl in waku!

What we rely on currently is the browser behaviour where it loads top level css first, but that's a bit complicated to implement, so I think React Float will be really helpful.

**Comment by Aslemammad** [comment]
Would be happy to be assigned.

**Comment by dai-shi** [comment]
I look forward you working on it. But, our priority is fixing bugs. I'll let you know the priority separately.

**Comment by Aslemammad** [comment]
Yea, as a discussion in [twitter](https://twitter.com/joshcstory/status/1759655916813885821) I don't think is this API is hmr friendly yet, we need to revisit this one later.

**Comment by dai-shi** [comment]
Thanks for the discussion!

> Long term we need to integrate this with fast refresh in React. 

Looking forward to that.

Closing this issue as not actionable. Let's revisit.
