### ISSUE TITLE
custom 404 support (static html only) for AWS Lambda and Partykit

### ISSUE THREAD

**Issue by dai-shi** [dai-shi/waku#509]
https://github.com/dai-shi/waku/pull/497#issuecomment-1951111788

- [x] AWS Lambda @aheissenberger
- [ ] Partykit @threepointone

**Comment by threepointone** [comment]
Whoops I missed it over the weekend, I'll do it soon.

**Comment by dai-shi** [comment]
a friendly reminder @threepointone

**Comment by threepointone** [comment]
yeah I'm working on this, I need to add a feature to partykit to do so. I hope to have it and will send a PR by monday!

**Comment by threepointone** [comment]
still working on this
