### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by kamuiiiii** [dai-shi/waku#523]
<img width="1214" alt="image" src="https://github.com/dai-shi/waku/assets/25859424/3859590c-b595-425d-9b2b-c6e3e9a414e8">
<img width="1213" alt="image" src="https://github.com/dai-shi/waku/assets/25859424/c1e77d2e-016f-48b4-a310-be5fe5951ebe">

**Comment by dai-shi** [comment]
How do you run examples?

**Comment by kamuiiiii** [comment]
reinstall dependencies solved the problem, thanks!
