### ISSUE TITLE
private dir / deploy aws-lambda / directory structure

### ISSUE THREAD

**Issue by aheissenberger** [dai-shi/waku#530]
**Error:**
```
2024-02-23 19:48:27.222 ERROR   Error: ENOENT: no such file or directory, open './private/data.json'
    at readFileSync (node:fs:453:20)
    at getData (file:///var/task/dist/templates/private-folder-page.js:18:31)
    at PrivateFolderPage (file:///var/task/dist/templates/private-folder-page.js:8:22)
    at ib (file:///var/task/dist/rsdw-server.js:562:7)
    at jb (file:///var/task/dist/rsdw-server.js:581:46)
    at P (file:///var/task/dist/rsdw-server.js:700:16)
    at Object.toJSON (file:///var/task/dist/rsdw-server.js:618:15)
    at stringify (<anonymous>)
    at nb (file:///var/task/dist/rsdw-server.js:814:53)
    at kb (file:///var/task/dist/rsdw-server.js:842:7) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './private/data.json'
```

**Problem:**
the current working directory of the deployed code is different to local dev environment

**local:** - the current working directory is `project`
```
project
   private
   src
   public
```

**deployed** - the current working directory is `task`
```
task
   dist
       private
       src
       public 
```

Using `readFileSync('./private/data.json', 'utf8')` fails as it will expect the folder here `./srv/private`

**sample code** from an async template:
```js
const getData = async () => {
  const jsonData=JSON.parse(readFileSync('./private/data.json', 'utf8'))
  const data = {
    jsonData
  };

  return data;
};
```

**Solutions:**
1) add an additional parameter to the the new plugin to handle path transformation during build process
2) only allow to access the private directory in code by accession the WAKU config value for `CONFIG_PRIVATE_DIR` -  which can be manipulated by the deployment adapter and gets replaced with the the final directory path

**Comment by dai-shi** [comment]
Just move `private` under `task`.
That's what we do for other cloud deployments.

As we discussed elsewhere, this may feel like a hack. We revisit this in the future and if it's too confusing, we consider dropping it.

By the way, why do you have `task/dist/src` in the deployed folder?

**Comment by aheissenberger** [comment]
The deployment tool [serverless framework](https://www.serverless.com) will build a zip from directories in the `project`directory.
I can include the `project/private` directory in the zip on the top layer. I tried to avoid this as it breaks the clean separation between build for deployment and deployment. The manual process to simply create a zip from the `dist` folder and deploy to aws becomes also more complex as you have to think about adding the `private` folder.

I close this for now by moving the handling of this to the deployment process.
