### ISSUE TITLE
`<a href="/[some_dynamic_page]"/>` will cause 404 in prod mode

### ISSUE THREAD

**Issue by himself65** [dai-shi/waku#536]
workaround is to use Link

**Comment by himself65** [comment]
Seems like it's the issue on dynamic page

**Comment by dai-shi** [comment]
Thanks for reporting. Can we reproduce it with examples/01_template with changing `render: 'dynamic'` for `path: '/'`?

**Comment by himself65** [comment]
> Thanks for reporting. Can we reproduce it with examples/01_template with changing `render: 'dynamic'` for `path: '/'`?

im adding the test case now

**Comment by himself65** [comment]
Oh, I think it's my custom app logic issue, here is fallback in waku start

```js
  if (!options.ssr) {
    // history api fallback
    app.use(
      '*',
      serveStatic({
        root: path.join(distDir, publicDir),
        rewriteRequestPath: () => '/',
      }),
    );
  }
```

**Comment by dai-shi** [comment]
what's your custom app logic? is your `options.ssr` false?

**Comment by himself65** [comment]
Yeah, I disabled SSR because it's a electron app, which run waku

**Comment by dai-shi** [comment]
Is it specific to `/`? I wonder if it causes the same issue with `path: '/foo/[id]'`.
It might be related to #534, which i'm currently working on.

**Comment by himself65** [comment]
Closing as this is not a bug in waku, but still need to update the document and cover the test

Solution: https://github.com/dai-shi/waku/issues/536#issuecomment-1963177880

**Comment by dai-shi** [comment]
Okay, I think I understand the problem.
When `/` is dynamic, we don't create `dist/public/index.html`,
then history api fallback doesn't work.
(I will think about it.)

**Comment by himself65** [comment]
> Okay, I think I understand the problem. When `/` is dynamic, we don't create `dist/public/index.html`, then history api fallback doesn't work. (I will think about it.)

Maybe we should fall back to SPA?
