### ISSUE TITLE
Question: Optional Tools in Create Usage

### ISSUE THREAD

**Issue by Yagasaki7K** [dai-shi/waku#625]
Wouldn't it be ideal to include selections during creation? For instance, choosing whether to have the application with TypeScript or JavaScript, and even with or without Tailwind.

I believe that in many cases, especially concerning Tailwind, it's more a matter of personal preference. Of course, there may be projects that need to use ChakraUI or MaterialUI, depending on the company, the project, or the developer's preference. Making this functionality optional would be more practical than having Tailwind as the default.

**Comment by dai-shi** [comment]
We will consider how we deal with it. For now, `create waku` can take `--example` option to specify a different template. So, it would be nice if we created a set of templates. Let's see if we can do it for the next patch release.
