### ISSUE TITLE
[BUG] Context Provider invalid value

### ISSUE THREAD

**Issue by kspeyanski** [dai-shi/waku#631]
Description:
Context value seems to not be what the `Provider` has set, but always fallback to the default one, when using `use client`.

Reproducible sandbox:
https://codesandbox.io/p/devbox/waku-x-kendo-forked-yp6m3f?file=%2Fsrc%2Ftemplates%2Fgrid-page.tsx%3A11%2C11

Steps to reproduce:
- Start the dev server
- navigate to the `/grid` page
- Observe the context's value

Expected result:
- The value should equal what's set through the `Context.Provider`

Actual result:
- The value is always what's set as a default in the `.createContext()` call.

**Comment by dai-shi** [comment]
Thanks for reporting.
It works in PRD, so it's DEV-only issue.
It works in v0.19.4, so it's probably #552 regression.
@Aslemammad

**Comment by Aslemammad** [comment]
Thank you so much, I'll look into this.

**Comment by Aslemammad** [comment]
The repro does not work for me 

![image](https://github.com/dai-shi/waku/assets/37929992/7c4dd5ac-d530-4d19-80e3-ac1c52105788)

**Comment by dai-shi** [comment]
Looks like the csb is changed and now the repro page is http://localhost/context.

**Comment by Aslemammad** [comment]
Nice, I'm taking a look.
