### ISSUE TITLE
Suspense doesn't work in layout with css modules (DEV-only)

### ISSUE THREAD

**Issue by dai-shi** [dai-shi/waku#639]
We have a tricky case in an example.

https://github.com/dai-shi/waku/blob/3b87654f39fc12592b1238e89e3423f105f41840/examples/09_cssmodules/src/components/Layout.tsx#L6-L20

It should show "Pending..." and then "Hello from server!".
However, it doesn't work as expected.

It seems like a regression in #446.
This is a dev-only issue.
@Aslemammad Can you investigate it please?

Here is a screencast that works before #446 commit.

https://github.com/dai-shi/waku/assets/490574/3e082901-5662-4360-84ef-085ae81c28ff

**Comment by Aslemammad** [comment]
I'll take a look.

**Comment by dai-shi** [comment]
The example is moved from `09_cssmodules` to `12_css` in #641.

**Comment by dai-shi** [comment]
working on it.
