### ISSUE TITLE
use monorepo packages stucture

### ISSUE THREAD

**Issue by himself65** [dai-shi/waku#64]
```
- packages
  - waku
  - create-waku
  - website
- examples
  - 01_xxx
  - 02_xxx
```

**Comment by dai-shi** [comment]
I have been generally against monorepo for my projects (especially `jotai`), but it actually makes sense for this project. In fact, I considered it once when I added `create-waku`, put it in `contrib` for the moment, and thought eventually move to monorepo.

I'm not very experienced with monorepo setup. Would you be able to help on it? I assume we use pnpm workspace.

**Comment by himself65** [comment]
I'm busy recently, but I will work on this if I have time.

**Comment by nickytonline** [comment]
Would the project want to go with [npm workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces), or something like [Nx](https://nx.dev/)?

**Comment by himself65** [comment]
Dont use nx :(

**Comment by himself65** [comment]
Pnpm workspace is enough. I have idea but no time to setup
