### ISSUE TITLE
[BUG]: wrong anchor link in the website

### ISSUE THREAD

**Issue by PerfectPan** [dai-shi/waku#649]
The website's anchor links appear to be incorrect, missing the original path, such as /blog/introducing-pages-router, as shown in the picture.

![CleanShot 2024-04-04 at 23 03 40@2x](https://github.com/dai-shi/waku/assets/24316656/0bd1d3cb-e0f8-4816-84b8-1938227215a4)

**Comment by sandren** [comment]
Thanks for reporting.

The root cause is an invalid `<base>` tag on nested routes:
https://github.com/dai-shi/waku/blob/main/packages/waku/src/lib/plugins/vite-plugin-rsc-index.ts#L80

**Comment by dai-shi** [comment]
https://github.com/dai-shi/waku/blob/e8ca9ac9646dfb6b108c94832b68fc838bfeb1a0/packages/waku/src/lib/plugins/vite-plugin-rsc-index.ts#L78-L80

Yeah, I knew it wasn't the right solution. So, it's a framework issue.
It may require someone's help. Help wanted.

**Comment by Aslemammad** [comment]
working on this!

**Comment by dai-shi** [comment]
by #697
