### ISSUE TITLE
expose build function for more customization

### ISSUE THREAD

**Issue by nihgwu** [dai-shi/waku#681]
I see right now config file is hardcoded as `waku.config.ts`, I think we can support `--config` to set it via CLI and move all output options like `--with-vercel` to `output: 'vercel' | 'netlify' ...`, as those are only used in build, doesn't make sense to have it globally

**Comment by dai-shi** [comment]
Yeah, there's some room for improvements.
Originally, we didn't have `waku.config.ts`, so there's some historical thing.
Stay tuned.

We generally don't want to use config file for normal users. So, we may still prefer output options.

**Comment by dai-shi** [comment]
I wonder if you prefer specifying config file name or stringified config object directly.

**Comment by nihgwu** [comment]
config file, there is a lib to do the job for you, to support all kinds of file types and even via package.json, and use js/ts if you need middleware

for cli user, I think we can rename `--with-vercel` to `--target=vercel` for easier maintenance

**Comment by nihgwu** [comment]
actually for me I can do without config file if we expose low level `build` method where I can set config directly 😄

**Comment by dai-shi** [comment]
> actually for me I can do without config file if we expose low level `build` method where I can set config directly 😄

Yeah, that's more customizable and aligns far better with my mental model.
Actually, we used to expose `build` function. We can surely do it, maybe with `unstable_` prefix. I'll work on it.
