### ISSUE TITLE
wrap sever action will cause runtime error

### ISSUE THREAD

**Issue by himself65** [dai-shi/waku#749]
See https://github.com/dai-shi/waku/pull/745

**Comment by himself65** [comment]
<img width="1015" alt="image" src="https://github.com/dai-shi/waku/assets/14026360/e3288965-7927-47d0-ae0e-2e6fc9b11982">

**Comment by himself65** [comment]
hot fix
<img width="758" alt="image" src="https://github.com/dai-shi/waku/assets/14026360/42cb15de-a89a-46a5-b919-4194cae2485e">

**Comment by dai-shi** [comment]
this should be fixed, right? let me know if it's not.
