### ISSUE TITLE
Strict Mode in pages router

### ISSUE THREAD

**Issue by aretrace** [dai-shi/waku#753]
`react-compiler-healthcheck` does not detect strict mode in the `npm create waku@latest` project template. It should be [on by default](https://github.com/dai-shi/waku/blob/81a7bc31bdb8a6a663cc4e78701789834fadfd05/packages/waku/src/lib/plugins/vite-plugin-rsc-managed.ts#L31), placing `<StrictMode>` tag on the root `_layout` works.

**Comment by dai-shi** [comment]
Thanks for reporting. Can anyone investigate it please?

**Comment by dai-shi** [comment]
#755 might be related.

**Comment by ojj1123** [comment]
This is the upstream issue.
I've tested the case: Next.js project with [`reactStrictMode: true` of `next.config.js`](https://nextjs.org/docs/pages/api-reference/next-config-js/reactStrictMode). But it also did shows `StrictMode usage not found.`
As this PR https://github.com/facebook/react/pull/30099, `react-compiler-healthcheck` just check whether or not there is `reactStrictMode: true` option.

So If we want the healthcheck detects the strict mode in waku project, we need to open the PR that `react-compiler-healthckeck` checks the strict mode in waku project. (But I don't think it is a good workaround.)

**Comment by ojj1123** [comment]
`react-compiler-healthcheck` just check whether or not js(x) files use `<React.StrictMode />` component.
As waku use `<StrictMode />` component by default internally, the healthcheck couldn't detect `StrictMode`

https://github.com/facebook/react/blob/fcfbfc1d1e3e350e1ea3fbc4a2418f647dc28a31/compiler/packages/react-compiler-healthcheck/src/checks/strictMode.ts#L24-L26

**Comment by dai-shi** [comment]
So, it's not an issue on our end, and it's probably not fixable?

**Comment by ojj1123** [comment]
Yeah, I think so.
If you want to fix it, you maybe open the PR on React. And this healthcheck needs to depend on Waku internal. So I think it's good to remain as non-fixable.
