### ISSUE TITLE
React DevTools doesn't detect Waku apps

### ISSUE THREAD

**Issue by dai-shi** [dai-shi/waku#755]
It only shows this:

![image](https://github.com/dai-shi/waku/assets/490574/7e985927-d70c-42ca-a8a6-277d289588a3)

Is anyone familiar with this problem?

**Comment by ojj1123** [comment]
Do you know how to reproduce?
I've been to get this error before but I don't know how to reproduce.

**Comment by dai-shi** [comment]
Doesn't it reproduce??

**Comment by ojj1123** [comment]
Yeah I've tried to repro but I couldn't.

I just did `pnpm create waku` and then `pnpm dev` for repro.

**Comment by dai-shi** [comment]
Did you install the React DevTools Chrome extension?

**Comment by dai-shi** [comment]
Hm, I just tried it again. It's working. Maybe, the extension is updated??

<img width="1079" alt="image" src="https://github.com/dai-shi/waku/assets/490574/87697633-2b11-4dc3-9c27-25f6525923e0">
