### ISSUE TITLE
Still having problems with composition

### ISSUE THREAD

**Issue by hipstersmoothie** [dai-shi/waku#782]
In a similar vein to my last react issue while upgrading I hit another (the last one was fixed though!)

[Here is the reproduction](https://github.com/hipstersmoothie/waku-repro-2)

Setup

```
pnpm I 
pnpm waku dev
```

Then visit http://localhost:3000/bench 

After that I get this error

![CleanShot 2024-07-05 at 02 02 54@2x](https://github.com/dai-shi/waku/assets/1192452/00f25e80-7976-494d-96dd-2ca5db1f8b20)

Oddly if I change this

![CleanShot 2024-07-05 at 02 04 27@2x](https://github.com/dai-shi/waku/assets/1192452/c08f6659-2bd6-447f-a825-06e7b6bdbd18)

To this

![CleanShot 2024-07-05 at 02 04 31@2x](https://github.com/dai-shi/waku/assets/1192452/cf518e38-d0ec-4c82-b80f-eda9a0e4acd7)

It works

**Comment by dai-shi** [comment]
Thanks for reporting!
Would you be able to identify which commit broke it? That would be super helpful.

**Comment by hipstersmoothie** [comment]
Which commit in the react repo or in waku? In waku it was the react version bump

As an aside, is react easy to build like that? I've never tried

**Comment by dai-shi** [comment]
> Which commit in the react repo or in waku?

I meant in waku.

> In waku it was the react version bump

Oh really. Then you may want to try different React version.
 
> As an aside, is react easy to build like that? I've never tried

It's not that difficult, but you can first try nightly builds, which is easier.
https://www.npmjs.com/package/react?activeTab=versions
`19.0.0-rc-<commit>-<date>`

**Comment by hipstersmoothie** [comment]
I've been trying new nightlies and it hasn't fixed the issue

Can't report this right now cause they have issues locked down to contributors

**Comment by jkhaui** [comment]
Can you post a screenshot of `node_modules > .vite > waku-dev-server` when the undefined error is thrown, and a 2nd screenshot of the same waku-dev-server directory when the error is "fixed"?

I have a feeling that the latest react 19 RCs are impacting how waku bundles ES modules in development

**Comment by dai-shi** [comment]
Please open new one if required.
