### ISSUE TITLE
Add scroll-related options to useRouter()

### ISSUE THREAD

**Issue by 9j** [dai-shi/waku#791]
Hello,

I've noticed a bug-like behavior when handling state with query parameters. Every time the query changes, the scroll position resets to the top of the page. This can be disruptive to the user experience, especially on pages with a lot of content.
To address this, I suggest adding scroll-related options to the useRouter() hook. This would allow developers to control scroll behavior when navigating or updating query parameters.

If you're open to it, I'd be willing to work on this feature. Would you be interested in a pull request that implements this functionality?

Thank you for your consideration.

**Comment by dai-shi** [comment]
Thanks for reporting.
We are pretty sensitive to add features with options to our API. (We generally prefer making API extensible instead.)
Can you simply fix the bug-like behavior?

https://github.com/dai-shi/waku/blob/4986822315b0a66997e2738bb0a6b177eb4bc3ec/packages/waku/src/router/client.ts#L428

Ah, I see. So, the current behavior is intentional. Do you want to keep the scroll position if only query param changes? Can you investigate how other frameworks handle it?

**Comment by dai-shi** [comment]
btw, I think `waku_new_path` is a hack. I wonder if there's better way of implementing it. Suggestions are welcome.

**Comment by 9j** [comment]
Thank you for your investigation and suggestion. Based on your findings, I'd like to propose the following solution for Waku:

Next.js has implemented a clever, albeit somewhat hacky, solution for maintaining scroll position using session storage. You can see this implementation in their router.ts file:

https://github.com/vercel/next.js/blob/96092dd42dc8d7fe4ef0b6ea9889020b2da2af86/packages/next/src/shared/lib/router/router.ts#L948

While this approach may not be the most elegant, it provides a seamless user experience. I believe Waku could benefit from a similar feature, allowing developers to optionally preserve scroll position during navigation.

My suggestion would be to implement a method in Waku's router that gives developers the ability to choose whether to maintain scroll position when pushing a new route. This could be achieved by adding an optional parameter to the push method, similar to Next.js's approach:

```typescript
router.push(url, { preserveScroll: true })
```

This would provide flexibility for developers to decide when to maintain scroll position and when to reset it, enhancing the overall user experience in Waku applications.

Would you be open to implementing such a feature? I'd be happy to work on a pull request if you think this would be a valuable addition to Waku.

**Comment by 9j** [comment]
I've investigated this issue and found an interesting approach in Next.js. They use session storage to save scroll coordinates, as shown in this code:

https://github.com/vercel/next.js/blob/96092dd42dc8d7fe4ef0b6ea9889020b2da2af86/packages/next/src/shared/lib/router/router.ts#L948-L967

While this method might seem a bit hacky, it provides a smooth user experience. I think it would be beneficial if Waku could implement a similar feature, allowing developers to optionally decide whether to preserve scroll position when pushing new routes or updating query parameters.

I'd like to propose a new approach for Waku.

The proposed method is `router.push(url, { preserveScroll: true })`. This approach can effectively maintain scroll position without using session storage like Next.js does.

The advantages of this approach are:

1. It can be implemented without significantly altering Waku's existing Router design.
2. It provides developers with flexibility to control scroll behavior.

This method could be simpler yet effective. It also seems like a good way to improve user experience while maintaining Waku's philosophy of API extensibility.

I'd be happy to work on a pull request to implement this feature if you're interested. What do you think about this approach? Please let me know if there are any additional considerations or modifications needed.

**Comment by dai-shi** [comment]
I agree that we shouldn't use sessionStorage.
What's the difference with our approach.
Can we do the same hack with `waku_new_path` without sessionStorage?

I agree adding an option `unstable_ preserveScroll` (with unstable prefix) is another good option which allows a user more control, but I would like to know what is impossible without such an option.

**Comment by rmarscher** [comment]
Yes, it would be nice for router.back() to have a similar option - or default to this behavior so it is similar to hitting the back button in the browser.

**Comment by dai-shi** [comment]
Yes, we would like to make it the default behavior (prefer less options), using `waku_new_path` hack.

Would you like to work on it?
