### ISSUE TITLE
Not possible to use a [...catchAll] route as the root page

### ISSUE THREAD

**Issue by jkhaui** [dai-shi/waku#797]
Hey,

I have a use-case for having a single `[...catchAll]` route at the project root instead of an `index.tsx` page, but this doesn't seem to work:

![image](https://github.com/user-attachments/assets/0cbfa8a1-b609-4adb-bb11-af792ff9cf91)

Any suggestions? Happy to submit a PR if you can point me in the right direction!

**Comment by jkhaui** [comment]
Hmm, realised I can have both a `[...catchAll]` and `index.tsx` at the root and this seems to work.

So I'll close this issue for now - I will try implementing a proper fix in future though

**Comment by dai-shi** [comment]
Oh, yeah, I think that's something we did. 👍
