### ISSUE TITLE
ExpressJS example ?

### ISSUE THREAD

**Issue by revskill10** [dai-shi/waku#80]
We do have express middleware, could you add an example on how to use with existing express server ? Thanks.

**Comment by alishahal100** [comment]
const express = require('express');
const app = express();

// Define your middleware function
function loggerMiddleware(req, res, next) {
  console.log(`Request: ${req.method} ${req.url}`);
  next();
}

// Apply the middleware to all routes
app.use(loggerMiddleware);

// Define your routes here
app.get('/', (req, res) => {
  res.send('Hello, World!');
});

// Start the server
app.listen(3000, () => {
  console.log('Server is running on port 3000');
});

**Comment by alishahal100** [comment]
const express = require('express');
const app = express();

// Define your custom middleware
const myMiddleware = (req, res, next) => {
  // Perform some logic or modify the request/response objects
  // For example, you can add a custom header to the response
  res.setHeader('X-Custom-Header', 'Hello from middleware!');
  
  // Call next() to move to the next middleware or route handler
  next();
};

// Register your middleware with the Express app
app.use(myMiddleware);

// Define your routes
app.get('/', (req, res) => {
  res.send('Hello, world!');
});

// Start the server
app.listen(3000, () => {
  console.log('Server is running on port 3000');
});

**Comment by revskill10** [comment]
@alishahal100 I mean the `waku` middleware.

**Comment by dai-shi** [comment]
Does this help?
https://github.com/dai-shi/waku/blob/62745b77289e53ba72a7e742b5a024672d849672/src/cli.ts#L88-L105
