### ISSUE TITLE
Slug with '.' seems to break the build output

### ISSUE THREAD

**Issue by tylerlaws0n** [dai-shi/waku#803]
To reproduce:

```sh
npm create waku@next
npm install
npm run build
```

Screenshot of build output:

<img width="194" alt="image" src="https://github.com/user-attachments/assets/72471282-c263-4cb6-828d-680de779ff19">

Each other slug creates `[slug]/index.html`, so I believe this is likely just an issue of escaping or replacing the `.` in Mr. Mime in this case.

I'd love to help with a PR for this, but wouldn't mind a nudge for where to start :)

**Comment by dai-shi** [comment]
Thanks for reporting! Yeah, sounds like a pattern matching issue. Can you open a PR please?
