### ISSUE TITLE
`public/index.html` missing from `dist` on initial build

### ISSUE THREAD

**Issue by tylerlaws0n** [dai-shi/waku#804]
```
npm create waku
npm install
npm run build -- --with-netlify-static # same happens for vercel static
```

`dist/public/index.html` does not exist, so the output is incomplete for use as a truly static site. Each other page seems to build just fine because they have index.html files, but not for the home route `/`.

Also would love to help with a PR on this one!

This project is awesome btw, thanks! A minimal way to use server components is super cool for the react ecosystem. 🎉

**Comment by dai-shi** [comment]
--with-netlify-static requires to be used with --with-netlify. Can you specify both and see how it goes?

**Comment by tylerlaws0n** [comment]
Interesting... Would you like for the CLI to error check to be sure `--with-foo` is present when `--with-foo-static` is present then?

I went and tried `waku build --with-netlify --with-netlify-static` and there is still unfortunately no `dist/public/index.html` file.

**Comment by dai-shi** [comment]
We will revisit CLI options later. For now, it's a known limitation.

I'm not sure what's happening. Maybe there's a bug.

**Comment by tylerlaws0n** [comment]
I am digging into this a bit now... just wanted to share the first thing that I find a bit odd: The build logs literally show `dist/public/index.html                        0.78 kB │ gzip:  0.39 kB` (full output below)

The file just doesn't exist after, so I am going to track down the log and work from there. 🔍 

```
vite v5.3.3 building SSR bundle for production...
✓ 60 modules transformed.
✓ built in 337ms
vite v5.3.3 building SSR bundle for production...
✓ 28 modules transformed.
✓ built in 78ms
vite v5.3.3 building SSR bundle for production...
✓ 61 modules transformed.
dist/assets/_layout-BbtALKRG.css                  15.13 kB
dist/assets/rsc1-463870183.js                      0.14 kB
dist/components/reload.js                          0.37 kB
dist/assets/index-wKma3wg8.js                      0.54 kB
dist/components/footer.js                          0.72 kB
dist/components/header.js                          1.02 kB
dist/assets/rsc2-dfef2ffe4.js                      1.16 kB
dist/pages/_layout.js                              1.34 kB
dist/waku-server.js                                1.55 kB
dist/assets/jsx-runtime.react-server-D8Wn-6Ej.js   1.79 kB
dist/assets/rsc0-7ffcdc24a.js                      2.15 kB
dist/pages/index.js                                3.25 kB
dist/pages/_slug_.js                               3.94 kB
dist/assets/react.react-server-CrJP5U_q.js        12.94 kB
dist/entries.js                                   19.95 kB
dist/rsdw-server.js                               90.78 kB
✓ built in 148ms
vite v5.3.3 building SSR bundle for production...
✓ 57 modules transformed.
dist/ssr/index.html                        0.91 kB
dist/ssr/waku-client.js                    0.31 kB
dist/ssr/assets/rsc1-463870183.js          0.52 kB
dist/ssr/assets/main-CIBiJ4wN.js           0.61 kB
dist/ssr/assets/indexHtml-CIBiJ4wN.js      0.61 kB
dist/ssr/assets/jsx-runtime-ChbgMHDT.js    1.21 kB
dist/ssr/assets/index-B4JICLj4.js          6.67 kB
dist/ssr/assets/rsc2-dfef2ffe4.js         13.33 kB
dist/ssr/react.js                         16.40 kB
dist/ssr/rsdw-client.js                   50.97 kB
dist/ssr/assets/rsc0-7ffcdc24a.js         57.34 kB
dist/ssr/rd-server.js                    385.99 kB
dist/ssr/assets/client-BRJsyWTL.js       471.71 kB
✓ built in 397ms
vite v5.3.3 building for production...
✓ 43 modules transformed.
dist/public/index.html                        0.78 kB │ gzip:  0.39 kB
dist/public/assets/rsc0-7ffcdc24a.js          0.22 kB │ gzip:  0.16 kB
dist/public/assets/main-CjOPLw-I.js           0.32 kB │ gzip:  0.22 kB
dist/public/assets/rsc1-463870183.js          0.34 kB │ gzip:  0.26 kB
dist/public/assets/jsx-runtime-BjG_zV1W.js    0.64 kB │ gzip:  0.42 kB
dist/public/assets/indexHtml-BnW-tO7u.js      1.03 kB │ gzip:  0.56 kB
dist/public/assets/rsc2-dfef2ffe4.js          6.44 kB │ gzip:  2.56 kB
dist/public/assets/client-CwIjRPSr.js        35.07 kB │ gzip: 11.55 kB
dist/public/assets/client-BE9zPung.js       169.90 kB │ gzip: 53.94 kB
✓ built in 236ms
```

**Comment by tylerlaws0n** [comment]
Realizing the build logs are just from vite... I attempted upgraded to vite latest (5.3.5) just to see if it was a known and fixed issue but it is not.

Next step will be to see if I can dig into vite and find the code around where the `dist/public/index.html` log is occurring.

**Comment by tylerlaws0n** [comment]
So the issue was with the `getConfig` function call. By default index.tsx has the following `getConfig`:

```ts
export const getConfig = async () => {
  return {
    render: "dynamic",
  };
};
```

Simply switching to "static" fixes the issue! Apologies for the false flag.

If you think any new docs could be helpful for this I am happy to add some, but this is genuinely just user error on my behalf. If no docs are necessary, please feel free to close this :)

**Comment by dai-shi** [comment]
Ah, I see what's happening.
Yes, we explicitly remove `public/index.html` for dynamic routes.

> If you think any new docs could be helpful for this I am happy to add some

I think it would be helpful. If you have an idea, feel free to open a PR and @sandren should be able to review it.
