### ISSUE TITLE
304 status code from the dev server changes to 404

### ISSUE THREAD

**Issue by mo36924** [dai-shi/waku#821]
The response of the status code 304 from the development server changes to the response of the status code 404, and waku does not operate normally.

Waku's version
waku: 0.21.0-beta.4
Node.js: 20.12.0

Steps to reproduce
```bash
npm create waku@next
cd waku-project
npm install
npm run dev
```
It would be easier to understand the problem if you open the devtools in your browser and refresh the screen with the cache disabled.

The response body of waku is undefined when the response cache from Vite's development server is in effect.
If the following middleware is added as a temporary measure, the response status code changes from 404 to 304 and the system operates normally.
```typescript
import type { Middleware } from "waku/config";

const middleware: Middleware = () => async (ctx, next) => {
  await next();
  if (ctx.res.status === 304 && !ctx.res.body) {
    ctx.res.body = new ReadableStream({
      start(controller) {
        controller.close();
      },
    });
  }
};

export default middleware;
```

Link to vite source code
https://github.com/vitejs/vite/blob/fcf50c2e881356ea0d725cc563722712a2bf5695/packages/vite/src/node/server/send.ts#L50-L54

**Comment by dai-shi** [comment]
Thanks for reporting. Sounds like nice catch.
Just to confirm, is this DEV only issue?

**Comment by mo36924** [comment]
Yes, this is DEV only issue.

**Comment by dai-shi** [comment]
Thanks for confirming. Yeah, I agree this should be fixed.

Have you looked into Waku source code? Do you have any insight where it should be fixed? (I know there's some place where it forces 404.)

**Comment by mo36924** [comment]
https://github.com/dai-shi/waku/blob/37445608bf4805b4f8adfebbb99bfc0bf0ef6dd6/packages/waku/src/lib/middleware/dev-server-impl.ts#L68-L73
It may be a good idea to modify the above as follows.
```typescript
if (controller) {
  controller.close();
  if (writable.writableEnded) {
    resolve(readable);
  } else if (!hasData) {
    resolve(null);
  }
}
```

**Comment by dai-shi** [comment]
Thanks. Hm, Can `writable.writableEnded` ever be `false` in `final`? In other words, wouldn't it hide the actual 404 case?

We might need to check `statusCode`.

**Comment by mo36924** [comment]
> Thanks. Hm, Can writable.writableEnded ever be false in final? 

Sure! It seems that writable.writableEnded will never be false in final.

At first I thought the problem was that if the Vite development server returned an empty response, the body would be null. However, it seems to be correct that the actual HTTP response without a body will be null.
https://developer.mozilla.org/en-US/docs/Web/API/Response/body

https://github.com/dai-shi/waku/blob/37445608bf4805b4f8adfebbb99bfc0bf0ef6dd6/packages/waku/src/lib/hono/runner.ts#L56-L62
It may be a good idea to modify the above as follows.
```typescript
if (ctx.res.body || ctx.res.status) {
  return c.body(
    ctx.res.body || null,
    (ctx.res.status as any) || 200,
    ctx.res.headers || {},
  );
}
```

Of course, a fix for #823 would not be a problem.

**Comment by dai-shi** [comment]
Yeah, sounds like a good idea.

**Comment by dai-shi** [comment]
#823 modified.

**Comment by mo36924** [comment]
Thanks for the PR.
LGTM #823
