### ISSUE TITLE
SSR build fails when files within nested components subdirectory import CJS module

### ISSUE THREAD

**Issue by jkhaui** [dai-shi/waku#824]
**Note:** I'll fill out this issue properly (with details and an example) when I have time. Just opening it first in case anyone's experienced similar behaviour and is able to investigate

I just fixed a very unusual problem where my app runs fine in dev, but would break during the SSR phase of a build (an error would be triggered by esm_loader).
There wasn't a clear indication of what was causing this. Eventually I found that moving a file out of `src/components/nested-directory` into something like `src/directory-a` fixed everything.

More details to come

**Comment by dai-shi** [comment]
> More details to come

@jkhaui A friendly reminder.

**Comment by jkhaui** [comment]
> @jkhaui A friendly reminder.

Sorry! I'm going to re-open this when I've time to provide a minimal repro
