### ISSUE TITLE
The waku package ships with its `src` files

### ISSUE THREAD

**Issue by dario-piotrowicz** [dai-shi/waku#826]
It seems like the `waku` package includes both `dist` and `src` files.

As you can see from my `node_modules` folder:
![Screenshot at 2024-08-11 13-34-13](https://github.com/user-attachments/assets/60383ba6-f816-49a9-8c6a-7fcb9028c6a0)

(or directly on [`npm`](https://www.npmjs.com/package/waku?activeTab=code))

This might be intentional (given that [`src` is included in the `package.json`](
https://github.com/dai-shi/waku/blob/main/packages/waku/package.json#L61)), but it seems pretty odd to me, so I figured I could just flag it here and check if it's actually intentional or now :slightly_smiling_face:  (on the top of my head I can't imagine why `src` files should be included in the production package)

**Comment by dai-shi** [comment]
Yes, it's intentional. I add `src` for most of my projects.
The rationale is that the npm registry should have a complete project.
But, I agree nowadays, we can rely on GitHub for `src`.
FWIW, my libs on pmndrs like [jotai](https://github.com/pmndrs/jotai) don't include `src`.

**Comment by dai-shi** [comment]
> The rationale is that the npm registry should have a complete project.

It's also because, in those cases, `dist` is bundled & minified.

Waku doesn't do it, so I'm fine to remove `src`.
