### ISSUE TITLE
Manual page refresh breaking starter site

### ISSUE THREAD

**Issue by aretrace** [dai-shi/waku#829]
When manually refreshing page on default `npm create waku@next` starter I get the following errors:
<br />
<img width="544" alt="image" src="https://github.com/user-attachments/assets/f1fe9379-987d-47d4-b346-2c178bb58000">
<hr />
<img width="544" alt="image" src="https://github.com/user-attachments/assets/6fc831b0-40cb-4a8d-a467-8adab3b21563">
<hr />
<img width="544" alt="image" src="https://github.com/user-attachments/assets/0fa64cb6-17e4-4e8d-8b0c-e68ceaf6c68a">
<br />
<br />
waku 0.21.0-beta.4

node v20.14.0
npm 10.7.0 | pnpm 9.7.0
both on chrome and safari

**Comment by dai-shi** [comment]
Thanks for reporting.
It looks like some cache headers break it.
Force Reload seems to work.
🤔

**Comment by dai-shi** [comment]
This doesn't reproduce if I run the example in the repo. 😢

**Comment by dai-shi** [comment]
Hm, I can't repro with the current `main`. Let's ship a new beta and see it.

**Comment by dai-shi** [comment]
`waku 0.21.0-beta.5` fixed it. (But, I don't know exactly what was the problem.)

**Comment by aretrace** [comment]
> (But, I don't know exactly what was the problem.)

Such is the nature of building software. 😅
