### ISSUE TITLE
`createRoot(...): Target container is not a DOM element.` randomly

### ISSUE THREAD

**Issue by himself65** [dai-shi/waku#83]
```
Uncaught Error: createRoot(...): Target container is not a DOM element.
    at aU (index-2e1e9bff.js:168:49419)
    at Object.SU [as createRoot] (index-2e1e9bff.js:171:7437)
    at xe (main-2f96bdb7.js:1:934)
    at main-2f96bdb7.js:14:2415
```

Source repo: https://github.com/toeverything/AFFiNE/tree/master/apps/docs

```shell
yarn install
cd apps/docs
yarn dev
```

**Comment by himself65** [comment]
See https://affine-developer.vercel.app/

And refresh page multiple times and sometimes you will see the error

**Comment by dai-shi** [comment]
related? https://www.sharooq.com/solved-createroot-target-container-is-not-a-dom-element

Does changing `async` to `defer` help?

**Comment by himself65** [comment]
Looks fix the bug

preview: https://affine-docs-git-himself65-fix-root-toeverything.vercel.app/
