### ISSUE TITLE
how to get current pathname in server component?

### ISSUE THREAD

**Issue by himself65** [dai-shi/waku#84]
```tsx
'use server';

const App = () => {
  // Does this possible
  const pathname = usePathname()
}
```

**Comment by dai-shi** [comment]
That's my next action item:
> Support interacting with server (req and res)

Stay tuned!

**Comment by himself65** [comment]
My workaround:

```tsx
const AppCreator = (pathname: string) => (props): ReactElement => {
  return (
    <div className="flex flex-col-reverse sm:flex-row">
      <nav className="w-full sm:w-64">
        <Sidebar />
      </nav>
      <main className="flex-1 p-6 w-full sm:w-[calc(100%-16rem)]">
        {/*<Editor />*/}
      </main>
    </div>
  );
};
```

```tsx
export default defineRouter(
  async id => {
    switch (id) {
      case 'index': {
        const { default: AppCreator } = await import('./src/app.js');
        return AppCreator(id)
      }
      default:
        return null;
    }
  },
  async () => {
    return ['index'];
  }
);
```

**Comment by himself65** [comment]
My workflow is to implement a document generator using waku (as you can see the code in https://github.com/toeverything/AFFiNE/tree/master/apps/docs).

So the logics are

1. get all possible paths
2. read the current `markdown` file from `current path`
3. render to the static RSC

**Comment by dai-shi** [comment]
I think that works too.

**Comment by dai-shi** [comment]
I thought something like #86 might help, but it actually doesn't because of caching.
I think returning a different component should be a canonical solution.
A little worried with your solution as it creates a new component every time, but it wouldn't be a big issue.

**Comment by lubieowoce** [comment]
isn't it possible to just pass a prop to the element in the router definition and thus avoid recreating the component? I did something like that here a while ago

https://github.com/lubieowoce/tangle/blob/9059cc35d75ab8c6e643df250275f06ee266c387/examples/router-in-waku/entries.ts#L67

**Comment by dai-shi** [comment]
Yeah, that's possible too. It's almost like making `getEntry` a component rather than a function.

Do you know how bad is `(path) => () => ...`?
