### ISSUE TITLE
unexpected cached result

### ISSUE THREAD

**Issue by himself65** [dai-shi/waku#85]
```ts
export default defineRouter(
  async id => {
    switch (id) {
      case 'index': {
        const { default: AppCreator } = await import('./src/app.js');
        return AppCreator({
          name: 'this is index'
        });
      }
      case 'about': {
        const { default: AppCreator } = await import('./src/app.js');
        return AppCreator({
          name: 'this is about'
        });
      }
      default:
        return null;
    }
  },
  async () => {
    return ['index', 'about'];
  }
);
```

```tsx
const App = ({ name = "Anonymous" }) => () => {
  return (
    <div style={{ border: "3px red dashed", margin: "1em", padding: "1em" }}>
      <h1>Hello {name}!!</h1>
      <h3>This is a server component.</h3>
    </div>
  );
};

export default App;
```

![image](https://github.com/dai-shi/waku/assets/14026360/be0c8c7e-83fa-4052-8bab-ce677ad59424)

![image](https://github.com/dai-shi/waku/assets/14026360/5b6f465c-2545-4e01-90aa-616bc4f793ec)

**Comment by dai-shi** [comment]
Hmm? I don't know how it's happening...
I can investigate it later. A full reproduction might be helpful.

**Comment by dai-shi** [comment]
Thanks! I know what's happening. It's not about caching.
Currently, waku/router supports nested routes in a unique way. It determines if it's a leaf route by the existence of `children`. (We may revisit it later as well as how to support nested routes from the ground.)

So, for now, you need to define your App component like the following:
```tsx
const App = ({ name = "Anonymous" }) => ({ children }) => {
  if (children) return children;
  return (
    <div style={{ border: "3px red dashed", margin: "1em", padding: "1em" }}>
      <h1>Hello {name}!!</h1>
      <h3>This is a server component.</h3>
    </div>
  );
};

export default App;
```

**Comment by dai-shi** [comment]
#124 will improve about caching (= no cache).
https://github.com/dai-shi/waku/issues/85#issuecomment-1608463397 approach is still valid and unchanged.
#124 will introduce a new api in `entries.tsx`, so it should be less confusing.

**Comment by dai-shi** [comment]
As I wasn't comfortable with caching, I made another change in #124.
Now, it has `layout.tsx` and `page.tsx` convention. So, this issue will officially be solved.
We will no longer need https://github.com/dai-shi/waku/issues/85#issuecomment-1608463397 workaround.
