### ISSUE TITLE
Dynamic routes on Cloudflare fail trying to import node:fs/promises

### ISSUE THREAD

**Issue by rmarscher** [dai-shi/waku#871]
The error in the workerd console is

```
Cannot process SSR Error: No such module "node:fs/promises".
    at null.<anonymous> (file:///waku-project/.wrangler/tmp/pages-tQnVbB/entries.js:485:11)
```

That is referencing [these changed lines](https://github.com/dai-shi/waku/pull/860/files#diff-dbb54d801e436acf21fb8afff808d82c614f9f0a7fc5e3ce8a666e437eef4d04L12-L55) in #860. Before that PR, Cloudflare workerd must have been getting routing information from `unstable_buildConfig[0].customData.data`.

To reproduce
npm create waku@0.9.3
cd waku-project
npm install

Then edit src/pages/about.tsx and change getConfig to dynamic:

```ts
export const getConfig = async () => {
  return {
    render: 'dynamic',
  };
};
```

Clone the waku repo.
cd packages/waku
pnpm i
pnpm run compile

Copy or link the built package to the waku project. I just replace the dist folder in node_modules/waku/dist.

In the waku project, run a cloudflare build and run a local workerd server via wrangler to serve the built files locally.

npm run build -- --with-cloudflare
npx wrangler pages dev dist

open http://localhost:8788/about in your browser.

**Comment by tylerlaws0n** [comment]
For this we could definitely add logic into the fs-router and build process for `--with-cloudflare` to polyfill `fs` when dynamic routes are present.

I'll defer to @dai-shi on whether or not that's an ideal approach or not with this though. I haven't looked into the plugins a ton, but maybe this would be considered a responsibility of a cloudflare plugin.

**Comment by rmarscher** [comment]
Thanks for giving it a look. I'm not sure polyfilling `fs` is necessary... it seems the `platformObject.buildData.fsRouterFiles` should be populated. If the build process could pass the fsRouterFiles to the build output vite plugin, it could write to a source file during build that can be imported at runtime and added to the platformObject via the platform server. 

For example, the platformObject here - https://github.com/dai-shi/waku/blob/main/packages/waku/src/lib/plugins/vite-plugin-deploy-cloudflare.ts#L86 - would need buildData.fsRouterFiles to be set. It could serialize that to a json file in the worker code bundle. That json file would be imported and passed to the waku server here https://github.com/dai-shi/waku/blob/main/packages/waku/src/lib/builder/serve-cloudflare.ts#L36-L38

**Comment by dai-shi** [comment]
Thanks for the catch. I'll have a look.
