### ISSUE TITLE
is api router needed?

### ISSUE THREAD

**Issue by vincenteof** [dai-shi/waku#88]
In waku, we have server action. I wonder whether we still need something like api router in Nextjs in this case. Is it a good practice to replace traditional requests with server actions?

**Comment by dai-shi** [comment]
Hi, thanks for opening up a discussion.
In general, we know very less about best practices, so there would be no conclusions at the moment.
That said, because a router would be helpful to have state in URL, even if server action works, routers would still provide some benefits.

**Comment by vincenteof** [comment]
Sorry for the  incorrect expression, actually I mean something like this: [API Routes](https://nextjs.org/docs/pages/building-your-application/routing/api-routes)
Since waku is based on express, it maybe not difficult to add this kind of support.

**Comment by dai-shi** [comment]
Oh, it's about api routes. Hm, yeah, if you want general api routes, you can just add such routes. Waku expose middlewares, so it's already supported.

Server action is still an open field to explore, but if all apis are based on it, we wouldn't need to use api routes.
