### ISSUE TITLE
Support `react-tweet`

### ISSUE THREAD

**Issue by dai-shi** [dai-shi/waku#90]
If we wanted to use https://github.com/vercel-labs/react-tweet, CSS Modules should be supported on server.

~Currently, it shows some errors with Vite ssrLoadModule.~ Fixed in #98 and WIP #105

We still have issues. Can anyone help?

**Comment by himself65** [comment]
What is the error? I think the logic here is to collect `*.module.css` files and append them to response html?

**Comment by dai-shi** [comment]
`ssrLoadModule` doesn't understand `.module.css` extension. It would be the easiest if we can simply ignore it.

**Comment by dai-shi** [comment]
Here's the error message. My expectation is that Waku doesn't handle the logic directly, but instead let Vite do it.

```
[vite] Error when evaluating SSR module /src/components/App.tsx: failed to import "/src/components/App.module.css"
|- TypeError: Cannot read properties of undefined (reading 'set')
    at TransformContext.transform (file:///.../waku/node_modules/.pnpm/vite@4.3.9_@types+node@20.3.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:37919:29)
    at async Object.transform (file:///.../waku/node_modules/.pnpm/vite@4.3.9_@types+node@20.3.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42919:30)
    at async loadAndTransform (file:///.../waku/node_modules/.pnpm/vite@4.3.9_@types+node@20.3.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:53385:29)
```

**Comment by dai-shi** [comment]
with #98 the error is gone, but there are no styles.

**Comment by dai-shi** [comment]
I will create a follow-up issue for #98 to support bare css modules.

**Comment by dai-shi** [comment]
#105 is created and this issue is specific to support `react-tweet.`

**Comment by dai-shi** [comment]
It seems to somewhat work for production build, but not for dev mode. We need someone who is familiar with Vite to help.

**Comment by Aslemammad** [comment]
#171 This might fix this.

**Comment by Aslemammad** [comment]
I'll work on this tomorrow! It's a matter of seeing if it works or not :)
