### ISSUE TITLE
(deploy/deno) unstable_getCustomContext doesn't work

### ISSUE THREAD

**Issue by dai-shi** [dai-shi/waku#908]
as well as `hono/context-storage`.

How to reproduce: deploy `08_cookies` example to Deno Deploy

It can be an upstream issue. Not sure.

**Comment by rmarscher** [comment]
Can you still reproduce this issue? I deployed here https://rm-waku-cookies-example-bkjhc9rcc5e1.deno.dev/

**Comment by dai-shi** [comment]
Yeah, it's working now. Thanks for checking.
