### ISSUE TITLE
(router) unstable_renderRoute causes a React error when jumping to a new page

### ISSUE THREAD

**Issue by dai-shi** [dai-shi/waku#937]
While working on #931, I noticed this issue. Did a hack but it broke another typical case. So, the issue is left for now.

## How to reproduce

- `npm run examples:dev:07_router`
- Click `Foo`
- Click `Jump to random page`

If it goes to `Jumping to /nested/bbb`, the following error is shown.

<img width="1259" alt="image" src="https://github.com/user-attachments/assets/3783b14e-eaca-4dbc-84cd-9f0217b6fcf8">

**Comment by kulkarnisaumitra98** [comment]
@dai-shi I think this bug doesn't seem to be valid anymore, in the lastest version 0.21.9, for the 21_create-pages example it doesn't seem to be reproducing after going to /nested/bbb

![image](https://github.com/user-attachments/assets/990b7bba-66d3-45b7-98f0-d3be2c89eb93)

**Comment by dai-shi** [comment]
Nice catch. Thanks for confirming!
