### ISSUE TITLE
Support NodeJS 22

### ISSUE THREAD

**Issue by rmarscher** [dai-shi/waku#942]
Warning during npm install:
```
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'waku@0.21.3',
npm warn EBADENGINE   required: { node: '^20.8.0 || ^18.17.0' },
npm warn EBADENGINE   current: { node: 'v22.9.0', npm: '10.9.0' }
npm warn EBADENGINE }
```

I have been running my local dev servers with 22.x and I haven't noticed any issues.

**Comment by himself65** [comment]
We already support it we just need update package.json I believe

**Comment by dai-shi** [comment]
Yeah, the question is if we run 3 versions in our CI. I feel like dropping node 18.

<img width="662" alt="image" src="https://github.com/user-attachments/assets/8574132d-80b8-4cb5-88cd-e798134bfba3">

node 20 becoming maintenance would be a good timing?

**Comment by dai-shi** [comment]
Or, maybe we can change the ci matrix from

| Node Version | Ubuntu              | macOS               | Windows             |
|--------------|---------------------|---------------------|---------------------|
| Node 18      | :heavy_check_mark:   | :heavy_check_mark:   | :heavy_check_mark:   |
| Node 20      | :heavy_check_mark:   | :heavy_check_mark:   | :heavy_check_mark:   |


to

| Node Version | Ubuntu              | macOS               | Windows             |
|--------------|---------------------|---------------------|---------------------|
| Node 18      | :heavy_check_mark:   |   |  |
| Node 20      | :heavy_check_mark:   |   |    |
| Node 22      | :heavy_check_mark:   |   :heavy_check_mark:   | :heavy_check_mark:    |

WDYT?

**Comment by himself65** [comment]
good to me, let me add then.

**Comment by himself65** [comment]
actually linux is almost same as macos, maybe we can remove it?

**Comment by dai-shi** [comment]
Let's keep it. Keep Ubuntu. What we should consider more is browser variations with this matrix.

**Comment by himself65** [comment]
No I mean remove macos

**Comment by dai-shi** [comment]
Keep macos just in case.

This should be good.

| Node Version | Ubuntu              | macOS               | Windows             |
|--------------|---------------------|---------------------|---------------------|
| Node 18      | :heavy_check_mark:   |   |  |
| Node 20      | :heavy_check_mark:   |   |    |
| Node 22      | :heavy_check_mark:   |   :heavy_check_mark:   | :heavy_check_mark:    |

**Comment by dai-shi** [comment]
> What we should consider more is browser variations with this matrix.

@himself65 What do you think about this?
We run e2e tests with various browsers, but maybe we run various browsers on node 22 & ubuntu, and for the rest chromium only?
Can we use ci matrix and specify browser for playwright? (I'm not sure how `--shard` works for now.)
