### ISSUE TITLE
Switch back to Cloudflare Workers

### ISSUE THREAD

**Issue by rmarscher** [dai-shi/waku#944]
Cloudflare recently launched this and it makes sense for us to switch back to it from Cloudflare Pages.
https://developers.cloudflare.com/workers/static-assets/

Other framework implementations are here - https://github.com/cloudflare/workers-sdk/tree/main/packages/create-cloudflare/templates-experimental

I'd also love to see waku included in their repo.

**Comment by dai-shi** [comment]
For reference, #795 is the one we switched from workers to pages.
