### ISSUE TITLE
Running `pnpm test` locally results in import/no-unresolved errors

### ISSUE THREAD

**Issue by tylersayshi** [dai-shi/waku#954]
When I run `pnpm test` locally, eslint fails with this import rule. In other projects, I often disable this import error since typescript already checks imports and more reliably.

I'm not suggesting to disable the rule here necessarily, but I would like to figure out how to fix it. And also, I'd like to understand how it succeeds in CI. I tried doing a fresh install of all my node_modules and still got the same errors

```sh
...

/Users/tyler/gitspace/waku/packages/create-waku/template/24_nesting/src/components/InnerApp.tsx
  1:26  error  Unable to resolve path to module 'react'  import/no-unresolved

/Users/tyler/gitspace/waku/packages/create-waku/template/24_nesting/src/main.tsx
  1:28  error  Unable to resolve path to module 'react'             import/no-unresolved
  2:41  error  Unable to resolve path to module 'react-dom/client'  import/no-unresolved

✖ 66 problems (66 errors, 0 warnings)
```

@himself65 is this something you'd be familiar with?

**Comment by himself65** [comment]
remove template files, it’s old and copy during build step

**Comment by tylersayshi** [comment]
Awesome, thanks!
