### ISSUE TITLE
create-waku Error: ENOENT: no such file or directory, open '../package.json'

### ISSUE THREAD

**Issue by tylersayshi** [dai-shi/waku#983]
The path that create waku is run is inconsistent from when we run it inside the project to when `npm create waku@latest` is run.

This causes the package.json to not be found, so we'll need to adjust for this.

I'm happy to dig into this, but wanted to note it here as being tracked.

**Comment by tylersayshi** [comment]
@dai-shi would you be able to publish a fix version for https://github.com/dai-shi/waku/pull/981 ? Calling `create waku@latest` throws this error right now

**Comment by dai-shi** [comment]
Yeah, I know this. I am hoping to release v0.21.6 soon, but if it takes time, I can do a hot fix.

**Comment by dai-shi** [comment]
v0.21.6 is out.
